import{TYPES,PERSON_ICONS,ALLERGIES,nastaveniePlochy,initialState,load,validProject,download}from'./state.js';
let state=load(),selectedItem='',editingGuest='',editingItem='',saveTimer,drag=null,space=false,history=[],future=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],els={world:$('#podorys'),items:$('#prvky'),viewport:$('#zobrazeniePodorysu'),library:$('#kniznicaPrvkov'),guestList:$('#zoznamHosti'),stats:$('#statistiky'),tableDetail:$('#detailStola')};
const uid=()=>globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)}),isTable=i=>i&&i.type.includes('table'),esc=s=>String(s??'');
const TRIEDY_TYPOV={'round-table':'okruhly-stol','rect-table':'obdlznikovy-stol','head-table':'hlavny-stol',chair:'stolicka',dj:'dj',speaker:'reproduktor',bar:'bar','dance-floor':'tanecny-parket',decoration:'dekoracia',plant:'rastlina',stage:'podium',photo:'fotokutik','universal-sharp':'univerzalny-ostry','universal-rounded':'univerzalny-obly'};
const TRIEDY_TVAROV={sharp:'tvar-ostry',rounded:'tvar-obly',circle:'tvar-kruh',chair:'tvar-stolicka',none:'tvar-bez-pozadia'};
const triedaTypu=type=>TRIEDY_TYPOV[type]||'vlastny-prvok';
const KLUC_PREDVOLENYCH_PRVKOV='wedding-planner-default-items-v1';
function kopiaPredvolenehoPrvku(item){return{type:String(item.type||''),name:String(item.name||''),x:Number(item.x)||0,y:Number(item.y)||0,width:Number(item.width)||40,height:Number(item.height)||40,rotation:Number(item.rotation)||0,number:Number(item.number)||0,seats:Number(item.seats)||0,note:String(item.note||''),locked:false,defaultKey:String(item.defaultKey||'')}}
function nacitajPredvolenePrvky(){try{const raw=localStorage.getItem(KLUC_PREDVOLENYCH_PRVKOV);if(raw){const data=JSON.parse(raw);if(Array.isArray(data)&&data.every(i=>i&&typeof i.type==='string'&&typeof i.defaultKey==='string'))return data.map(kopiaPredvolenehoPrvku)}}catch(error){console.error('Predvolené rozloženie sa nepodarilo načítať.',error)}return initialState().items.map(kopiaPredvolenehoPrvku)}
function zapisPredvolenePrvky(prvky){try{localStorage.setItem(KLUC_PREDVOLENYCH_PRVKOV,JSON.stringify(prvky));return true}catch(error){console.error('Predvolené rozloženie sa nepodarilo uložiť.',error);toast('Predvolený prvok sa nepodarilo uložiť');return false}}
function ulozPredvolenyPrvok(item,oznamenie=false){if(!nastaveniePlochy.editovatelnyRezim||!item)return false;if(!item.defaultKey)item.defaultKey=`vlastny-${uid()}`;const prvky=nacitajPredvolenePrvky(),index=prvky.findIndex(i=>i.defaultKey===item.defaultKey),kopia=kopiaPredvolenehoPrvku(item);if(index>=0)prvky[index]=kopia;else prvky.push(kopia);const ulozene=zapisPredvolenePrvky(prvky);if(ulozene&&oznamenie)toast('Prvok bol uložený ako predvolený');return ulozene}
function odstranPredvolenyPrvok(item){if(!nastaveniePlochy.editovatelnyRezim||!item?.defaultKey)return true;return zapisPredvolenePrvky(nacitajPredvolenePrvky().filter(i=>i.defaultKey!==item.defaultKey))}
function vytvorStavSPredvolenymiPrvkami(){const novy=initialState(),povodne=novy.items.slice(),klucPodlaId=new Map(povodne.map(i=>[i.id,i.defaultKey])),predvolene=nacitajPredvolenePrvky(),idPodlaKluca=new Map();novy.items=predvolene.map(item=>{const kopia={...kopiaPredvolenehoPrvku(item),id:uid(),locked:false};idPodlaKluca.set(kopia.defaultKey,kopia.id);return kopia});novy.guests.forEach(host=>{if(!host.tableId)return;const kluc=klucPodlaId.get(host.tableId),noveId=idPodlaKluca.get(kluc),stol=novy.items.find(i=>i.id===noveId);if(noveId&&stol&&+host.seatNumber<=stol.seats)host.tableId=noveId;else{host.tableId='';host.seatNumber=null}});return novy}
function toast(t){const e=$('#oznam');e.textContent=t;e.classList.add('zobrazene');setTimeout(()=>e.classList.remove('zobrazene'),1800)}
function doplnTlacidloZamku(){const actions=els.items.querySelector('.prvok-podorysu.vybrane .akcie-prvku');if(!actions||actions.querySelector('.zamknutie-prvku'))return;const item=state.items.find(i=>i.id===selectedItem);if(!item)return;const button=document.createElement('button');button.type='button';button.className='zamknutie-prvku'+(item.locked?' aktivne':'');button.append(createVisualIcon('fa_lock'));button.title=item.locked?'Odomknúť polohu':'Uzamknúť polohu';button.setAttribute('aria-label',button.title);button.setAttribute('aria-pressed',String(item.locked));button.onclick=e=>{e.stopPropagation();snapshot();item.locked=!item.locked;renderItems();changed();toast(item.locked?'Poloha objektu bola uzamknutá':'Poloha objektu bola odomknutá')};actions.insertBefore(button,actions.querySelector('.odstranit'))}
const sledovanieAkciiPrvku=new MutationObserver(doplnTlacidloZamku);sledovanieAkciiPrvku.observe(els.items,{childList:true,subtree:true});
function formDataObject(form){const result={};new FormData(form).forEach((value,key)=>{result[key]=value});return result}
function showDialog(dialog){if(typeof dialog.showModal==='function')dialog.showModal();else{dialog.setAttribute('open','');dialog.classList.add('nahradny-dialog')}}
function closeDialog(dialog){if(typeof dialog.close==='function')dialog.close();else{dialog.removeAttribute('open');dialog.classList.remove('nahradny-dialog')}}
function createVisualIcon(value,className=''){const icon=String(value||'');if(icon.startsWith('fa_')){const element=document.createElement('i');element.className=`fa-sharp fa-light fa-${icon.slice(3).replace(/_/g,'-')} vizualna-ikona ${className}`;element.setAttribute('aria-hidden','true');return element}if(icon.toLowerCase().endsWith('.svg')){const image=document.createElement('img');image.className=`vizualna-ikona svg-ikona ${className}`;image.src=icon.startsWith('assets/')?icon:`assets/${icon}`;image.alt='';image.draggable=false;return image}const fallback=document.createElement('span');fallback.className=`vizualna-ikona ${className}`;fallback.textContent=icon;return fallback}
function fillItemVisual(container,icon,label,visibility={icon:true,text:true}){const nodes=[],showIcon=visibility.icon!==false,showText=visibility.text!==false;container.classList.toggle('iba-ikona',showIcon&&!showText);container.classList.toggle('iba-text',!showIcon&&showText);if(showIcon){const visual=createVisualIcon(icon,'ikona-prvku');if(visibility.iconColor)visual.style.color=visibility.iconColor;nodes.push(visual)}if(showText){const text=document.createElement('span');text.className='nazov-prvku';text.textContent=label;nodes.push(text)}container.replaceChildren(...nodes)}
function shapeClass(def){return TRIEDY_TVAROV[def?.[6]?.shape]||TRIEDY_TVAROV.sharp}
window.closePlannerDialog=closeDialog;
function snapshot(){history.push(JSON.stringify(state));if(history.length>40)history.shift();future=[]}
function changed(){state.meta.updatedAt=new Date().toISOString();clearTimeout(saveTimer);saveTimer=setTimeout(save,1000);renderStats()}
function save(){try{localStorage.setItem('wedding-planner-v1',JSON.stringify(state))}catch(error){console.error('Projekt sa nepodarilo uložiť.',error)}}
function renderAll(){setTransform();renderItems();renderGuests();renderStats();renderEvent();if(selectedItem)renderTableDetail()}
function setTransform(){els.world.style.transform=`translate(${state.settings.panX}px,${state.settings.panY}px) scale(${state.settings.zoom})`}
function renderLibrary(){TYPES.forEach(def=>{const[type,name,icon]=def,d=document.createElement('div'),label=document.createElement('span'),iconWrap=document.createElement('span'),visual=createVisualIcon(icon);d.className='polozka-kniznice';d.dataset.type=type;iconWrap.className='ikona-kniznice';if(def[6]?.iconColor)visual.style.color=def[6].iconColor;iconWrap.append(visual);label.textContent=name;d.append(iconWrap,label);d.addEventListener('pointerdown',libraryPointer);els.library.append(d)})}
els.library.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<=Math.abs(e.deltaX))return;e.preventDefault();els.library.scrollLeft+=e.deltaY},{passive:false});
function addItem(type,x,y){snapshot();const def=TYPES.find(t=>t[0]===type),n=state.items.filter(i=>i.type===type).length+1;state.items.push({id:uid(),type,name:def[1]+' '+n,x,y,width:def[3],height:def[4],rotation:0,number:n,seats:def[5],note:'',locked:false,defaultKey:''});selectedItem=state.items[state.items.length-1].id;renderItems();changed()}
function libraryPointer(e){if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();const card=e.currentTarget,type=card.dataset.type,def=TYPES.find(t=>t[0]===type),startX=e.clientX,startY=e.clientY,preview=document.createElement('div'),shape=document.createElement('div');preview.className=`nahlad-presunu ${triedaTypu(type)} ${shapeClass(def)}`;preview.style.width=Math.max(60,Math.min(160,def[3]*.55))+'px';preview.style.height=Math.max(50,Math.min(110,def[4]*.55))+'px';shape.className='tvar-prvku';fillItemVisual(shape,def[2],def[1],{...def[6],icon:true,text:false});preview.append(shape);document.body.append(preview);drag={library:type};card.classList.add('presuvane');card.setPointerCapture(e.pointerId);const move=ev=>{const distance=Math.hypot(ev.clientX-startX,ev.clientY-startY);preview.style.left=ev.clientX+'px';preview.style.top=ev.clientY+'px';if(distance>5)preview.classList.add('viditelne')};const cleanup=()=>{card.classList.remove('presuvane');preview.remove();drag=null;card.removeEventListener('pointermove',move);card.removeEventListener('pointerup',up);card.removeEventListener('pointercancel',cancel)};const up=ev=>{const r=els.viewport.getBoundingClientRect(),distance=Math.hypot(ev.clientX-startX,ev.clientY-startY),target=document.elementFromPoint(ev.clientX,ev.clientY),overLibrary=target&&target.closest('.obal-kniznice');if(distance>8&&!overLibrary&&ev.clientX>r.left&&ev.clientX<r.right&&ev.clientY>r.top&&ev.clientY<r.bottom){const p=screenToWorld(ev.clientX,ev.clientY);addItem(type,p.x-def[3]/2,p.y-def[4]/2)}cleanup()};const cancel=()=>cleanup();card.addEventListener('pointermove',move);card.addEventListener('pointerup',up);card.addEventListener('pointercancel',cancel)}
function screenToWorld(x,y){const r=els.viewport.getBoundingClientRect(),z=state.settings.zoom;return{x:(x-r.left-state.settings.panX)/z,y:(y-r.top-state.settings.panY)/z}}
function renderItems(){els.items.replaceChildren();state.items.forEach(i=>{const d=document.createElement('div'),def=TYPES.find(t=>t[0]===i.type);d.className=`prvok-podorysu ${triedaTypu(i.type)} ${shapeClass(def)}${i.id===selectedItem?' vybrane':''}${i.locked?' zamknute':''}`;d.dataset.id=i.id;Object.assign(d.style,{left:i.x+'px',top:i.y+'px',width:i.width+'px',height:i.height+'px',transform:`rotate(${Number(i.rotation)||0}deg)`});const sh=document.createElement('div');sh.className='tvar-prvku';fillItemVisual(sh,def?def[2]:'',i.name,def&&def[6]?def[6]:{icon:true,text:true});d.append(sh);if(isTable(i))renderSeats(d,i);if(i.id===selectedItem){const actions=document.createElement('div');actions.className='akcie-prvku';actions.addEventListener('pointerdown',e=>e.stopPropagation());const edit=document.createElement('button');edit.type='button';edit.append(createVisualIcon('fa_pen'));edit.title='Upraviť objekt';edit.onclick=e=>{e.stopPropagation();openItem(i.id)};actions.append(edit);if(nastaveniePlochy.editovatelnyRezim){const predvolene=document.createElement('button'),bodka=document.createElement('span');predvolene.type='button';predvolene.className='ulozit-predvolene'+(i.defaultKey?' je-predvolene':'');predvolene.title=i.defaultKey?'Aktualizovať predvolený prvok':'Uložiť ako predvolený prvok';predvolene.setAttribute('aria-label',predvolene.title);bodka.className='zelena-bodka';predvolene.append(bodka);predvolene.onclick=e=>{e.stopPropagation();snapshot();if(ulozPredvolenyPrvok(i,true)){renderItems();changed()}};actions.append(predvolene)}const duplicate=document.createElement('button');duplicate.type='button';duplicate.append(createVisualIcon('fa_copy'));duplicate.title='Duplikovať objekt';duplicate.onclick=e=>{e.stopPropagation();duplicateObject(i.id)};const remove=document.createElement('button');remove.type='button';remove.append(createVisualIcon('fa_xmark'));remove.title='Odstrániť objekt';remove.className='odstranit';remove.onclick=e=>{e.stopPropagation();removeObject(i.id)};actions.append(duplicate,remove);d.append(actions)}d.addEventListener('pointerdown',itemPointer);d.addEventListener('dblclick',()=>openItem(i.id));d.addEventListener('click',e=>{e.stopPropagation();selectedItem=i.id;renderItems();if(isTable(i)){openTab('table');renderTableDetail()}});els.items.append(d)})}
function renderSeats(parent,item){for(let n=1;n<=item.seats;n++){const s=document.createElement('button'),a=(n/item.seats)*Math.PI*2-Math.PI/2,rx=item.width/2+25,ry=item.height/2+25,g=state.guests.find(x=>x.tableId===item.id&&+x.seatNumber===n);s.className='miesto'+(g?' obsadene':'')+(g?.allergies.length?' ma-alergiu':'')+(g?.personType==='child'?' dieta':'');if(item.type==='head-table'){s.style.left=item.width*n/(item.seats+1)+'px';s.style.top='-24px'}else{s.style.left=item.width/2+Math.cos(a)*rx+'px';s.style.top=item.height/2+Math.sin(a)*ry+'px'}s.textContent=g?((g.firstName?.[0]||'')+(g.lastName?.[0]||'')):n;if(g){const cislo=document.createElement('span');cislo.className='cislo-obsadeneho-miesta';cislo.textContent=n;s.append(cislo)}if(g?.personType==='child')s.append(createVisualIcon(PERSON_ICONS.child,'ikona-osoby-na-mieste'));s.title=g?`${g.firstName} ${g.lastName} · miesto ${n}`:`Miesto ${n}`;s.addEventListener('pointerdown',e=>e.stopPropagation());s.addEventListener('click',e=>{e.stopPropagation();selectedItem=item.id;openTab('table');renderTableDetail(n)});s.addEventListener('dragover',e=>e.preventDefault());s.addEventListener('drop',e=>{e.preventDefault();assignGuest(e.dataTransfer.getData('text/guest'),item.id,n)});parent.append(s)}}
function itemPointer(e){if(e.button!==0)return;const i=state.items.find(x=>x.id===e.currentTarget.dataset.id);if(!i||i.locked)return;e.stopPropagation();snapshot();const p=screenToWorld(e.clientX,e.clientY),ox=i.x-p.x,oy=i.y-p.y,node=e.currentTarget;node.setPointerCapture(e.pointerId);const move=ev=>{const q=screenToWorld(ev.clientX,ev.clientY);i.x=Math.round(q.x+ox);i.y=Math.round(q.y+oy);node.style.left=i.x+'px';node.style.top=i.y+'px'};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);if(i.defaultKey)ulozPredvolenyPrvok(i);changed()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up)}
function renderStats(){const tables=state.items.filter(isTable),capacity=tables.reduce((a,t)=>a+t.seats,0),seated=state.guests.filter(g=>g.tableId).length,vals=[['Hostia',state.guests.length],['Dospelí',state.guests.filter(g=>g.personType==='adult').length],['Deti',state.guests.filter(g=>g.personType==='child').length],['Stoly',tables.length],['Obsadené',seated],['Voľné miesta',Math.max(0,capacity-seated)],['Alergie',state.guests.filter(g=>g.allergies.length).length],['Bez miesta',state.guests.length-seated]];els.stats.replaceChildren(...vals.map(([l,v])=>{const d=document.createElement('div');d.className='statistika';const s=document.createElement('small'),b=document.createElement('b');s.textContent=l;b.textContent=v;d.append(s,b);return d}))}
function renderGuests(){const q=$('#hladanieHosta').value.toLowerCase(),f=$('#filterHosti').value;els.guestList.replaceChildren();state.guests.filter(g=>{const m=(g.firstName+' '+g.lastName).toLowerCase().includes(q);return m&&(f==='all'||f==='unseated'&&!g.tableId||f==='allergy'&&g.allergies.length||f==='child'&&g.personType==='child')}).forEach(g=>{const t=state.items.find(i=>i.id===g.tableId),d=document.createElement('div');d.className='riadok-hosta';d.draggable=true;d.addEventListener('dragstart',e=>e.dataTransfer.setData('text/guest',g.id));const av=document.createElement('div');av.className='ikona-hosta';av.append(createVisualIcon(PERSON_ICONS[g.personType]||PERSON_ICONS.adult));const info=document.createElement('div'),b=document.createElement('b'),sm=document.createElement('small');b.textContent=g.firstName+' '+g.lastName;sm.textContent=(g.personType==='child'?'Dieťa':'Dospelý')+' · '+(t?`${t.name}, miesto ${g.seatNumber}`:'Bez miesta');info.append(b,sm);g.allergies.forEach(a=>{const x=document.createElement('span');x.className='stitok';x.textContent=a;info.append(x)});const acts=document.createElement('div');acts.className='akcie-hosta';const edit=document.createElement('button');edit.append(createVisualIcon('fa_pen'));edit.title='Upraviť';edit.onclick=()=>openGuest(g.id);const del=document.createElement('button');del.append(createVisualIcon('fa_xmark'));del.title='Odstrániť';del.onclick=()=>{if(confirm('Odstrániť hosťa?')){snapshot();state.guests=state.guests.filter(x=>x.id!==g.id);renderAll();changed()}};acts.append(edit,del);d.append(av,info,acts);els.guestList.append(d)})}
function assignGuest(gid,tid,seat){const g=state.guests.find(x=>x.id===gid);if(!g)return;const occupied=state.guests.find(x=>x.tableId===tid&&+x.seatNumber===+seat&&x.id!==gid);if(occupied&&!confirm(`Miesto je obsadené hosťom ${occupied.firstName}. Vymeniť?`))return;snapshot();if(occupied){occupied.tableId='';occupied.seatNumber=null}g.tableId=tid;g.seatNumber=seat;renderAll();changed()}
function renderTableDetail(focusSeat){const t=state.items.find(i=>i.id===selectedItem);if(!isTable(t)){els.tableDetail.innerHTML='<div class="prazdne"><b>Vyberte stôl</b></div>';return}els.tableDetail.replaceChildren();const head=document.createElement('div');head.className='hlavicka-sekcie';const h=document.createElement('h2');h.textContent=t.name;const edit=document.createElement('button');edit.textContent='Upraviť stôl';edit.onclick=()=>openItem(t.id);head.append(h,edit);const map=document.createElement('div');map.className='mapa-miest '+(t.type==='round-table'?'':'obdlznikova')+(t.type==='head-table'?' hlavny':'');const table=document.createElement('div');table.className='nahlad-stola';table.textContent=t.number?`Stôl ${t.number}`:t.name;map.append(table);for(let n=1;n<=t.seats;n++){const a=n/t.seats*Math.PI*2-Math.PI/2,g=state.guests.find(x=>x.tableId===t.id&&+x.seatNumber===n),s=document.createElement('button');s.className='detail-miesta'+(g?' obsadene':'');if(t.type==='head-table'){s.style.left=8+n/(t.seats+1)*84+'%';s.style.top='20%'}else{s.style.left=50+Math.cos(a)*42+'%';s.style.top=50+Math.sin(a)*42+'%'}s.textContent=g?g.firstName:n;s.title=g?`${g.firstName} ${g.lastName}`:`Miesto ${n}`;s.onclick=()=>seatEditor(t,n,g);s.ondragover=e=>e.preventDefault();s.ondrop=e=>assignGuest(e.dataTransfer.getData('text/guest'),t.id,n);map.append(s)}els.tableDetail.append(head,map);if(focusSeat){const g=state.guests.find(x=>x.tableId===t.id&&+x.seatNumber===focusSeat);seatEditor(t,focusSeat,g)}}
function seatEditor(t,n,g){let box=$('#editorMiesta');if(box)box.remove();box=document.createElement('div');box.id='editorMiesta';const label=document.createElement('b');label.textContent=`Miesto ${n}`;const help=document.createElement('small');help.textContent=g?'Priradený hosť':'Vyberte hosťa zo zoznamu alebo vytvorte nového';const sel=document.createElement('select');const empty=document.createElement('option');empty.value='';empty.textContent='— Voľné miesto —';sel.append(empty);state.guests.filter(x=>!x.tableId||x.id===g?.id).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.firstName+' '+x.lastName;o.selected=x.id===g?.id;sel.append(o)});sel.onchange=()=>sel.value?assignGuest(sel.value,t.id,n):(g&&(snapshot(),g.tableId='',g.seatNumber=null,renderAll(),changed()));const action=document.createElement('button');action.type='button';action.className='hlavne';action.textContent=g?'Upraviť hosťa':'＋ Pridať nového hosťa';action.onclick=()=>g?openGuest(g.id):openGuest('',{tableId:t.id,seatNumber:n});box.append(label,help,sel,action);if(g){const summary=document.createElement('div');summary.className='suhrn-hosta-na-mieste';const allergies=document.createElement('p'),allergiesLabel=document.createElement('b');allergiesLabel.textContent='Alergie: ';allergies.append(allergiesLabel,document.createTextNode(g.allergies?.length?g.allergies.join(', '):'žiadne'));summary.append(allergies);if(g.note?.trim()){const note=document.createElement('p'),noteLabel=document.createElement('b');noteLabel.textContent='Poznámka: ';note.append(noteLabel,document.createTextNode(g.note.trim()));summary.append(note)}box.append(summary)}els.tableDetail.append(box)}
function openGuest(id='',assignment=null){editingGuest=id;const g=state.guests.find(x=>x.id===id)||{firstName:'',lastName:'',personType:'adult',tableId:assignment?assignment.tableId:'',seatNumber:assignment?assignment.seatNumber:'',allergies:[],note:''};$('#nadpisDialoguHosta').textContent=id?'Upraviť hosťa':'Pridať hosťa';const f=$('#formularHosta');['firstName','lastName','personType','seatNumber','note'].forEach(k=>f.elements[k].value=g[k]??'');const ts=f.elements.tableId;ts.replaceChildren(new Option('Bez miesta',''),...state.items.filter(isTable).map(t=>new Option(t.name,t.id)));ts.value=g.tableId||'';$('#vyberAlergii').replaceChildren(...ALLERGIES.map(a=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.value=a;c.checked=g.allergies.includes(a);l.append(c,document.createTextNode(a));return l}));showDialog($('#dialogHosta'))}
$('#formularHosta').addEventListener('submit',e=>{e.preventDefault();const obj=formDataObject(e.currentTarget);if(!obj.firstName.trim())return;const seat=+obj.seatNumber||null;if(obj.tableId&&seat){const t=state.items.find(x=>x.id===obj.tableId);if(!t||seat>t.seats)return toast('Neplatné číslo miesta');const occ=state.guests.find(x=>x.tableId===obj.tableId&&+x.seatNumber===seat&&x.id!==editingGuest);if(occ)return toast('Toto miesto je už obsadené')}snapshot();const old=state.guests.find(x=>x.id===editingGuest);const g={...(old||{id:uid(),color:'#d98a8f'}),...obj,seatNumber:seat,allergies:$$('#vyberAlergii input:checked').map(x=>x.value)};delete g.childAge;delete g.menu;delete g.companion;delete g.group;delete g.rsvp;if(old){Object.keys(old).forEach(key=>delete old[key]);Object.assign(old,g)}else state.guests.push(g);closeDialog($('#dialogHosta'));renderAll();changed()});
function openItem(id){editingItem=id;const i=state.items.find(x=>x.id===id),f=$('#formularPrvku');['name','number','width','height','rotation','seats','note'].forEach(k=>f.elements[k].value=i[k]??'');f.elements.seats.disabled=!isTable(i);$$('.iba-pre-stol').forEach(x=>x.style.display=isTable(i)?'block':'none');$('#zamknutPrvok').textContent=i.locked?'Odomknúť':'Uzamknúť';showDialog($('#dialogPrvku'))}
$('#formularPrvku').addEventListener('submit',e=>{e.preventDefault();const i=state.items.find(x=>x.id===editingItem);if(!i)return;const f=e.currentTarget,d=formDataObject(f);if(typeof f.reportValidity==='function'&&!f.reportValidity())return;snapshot();Object.assign(i,{name:String(d.name||i.name).slice(0,80),number:Number(d.number)||0,width:Math.min(800,Math.max(40,Number(d.width)||i.width)),height:Math.min(800,Math.max(40,Number(d.height)||i.height)),rotation:Number(d.rotation)||0,seats:isTable(i)?Math.min(30,Math.max(1,Number(d.seats)||1)):0,note:String(d.note||'').slice(0,500)});if(i.defaultKey)ulozPredvolenyPrvok(i);closeDialog($('#dialogPrvku'));renderAll();changed();toast('Objekt bol uložený')});
function removeObject(id){const item=state.items.find(x=>x.id===id);if(!item)return;snapshot();odstranPredvolenyPrvok(item);state.guests.filter(g=>g.tableId===id).forEach(g=>{g.tableId='';g.seatNumber=null});state.items=state.items.filter(x=>x.id!==id);selectedItem='';editingItem='';if($('#dialogPrvku').open)closeDialog($('#dialogPrvku'));renderAll();renderTableDetail();changed()}
function duplicateObject(id){const i=state.items.find(x=>x.id===id);if(!i)return;snapshot();const c={...i,id:uid(),name:i.name+' – kópia',x:i.x+35,y:i.y+35,number:state.items.filter(x=>x.type===i.type).length+1,locked:false,defaultKey:''};state.items.push(c);if($('#dialogPrvku').open)closeDialog($('#dialogPrvku'));selectedItem=c.id;renderAll();changed();toast('Objekt bol duplikovaný')}
$('#odstranitPrvok').onclick=()=>removeObject(editingItem);$('#duplikovatPrvok').onclick=()=>duplicateObject(editingItem);$('#zamknutPrvok').onclick=()=>{const i=state.items.find(x=>x.id===editingItem);snapshot();i.locked=!i.locked;closeDialog($('#dialogPrvku'));renderAll();changed()};
function openTab(name){const panely={overview:'#panelPrehladu',table:'#panelStola',event:'#panelPodujatia'};$$('.zalozky-panelu button').forEach(b=>b.classList.toggle('aktivne',b.dataset.tab===name));$$('.obsah-zalozky').forEach(p=>p.classList.remove('aktivne'));const panel=$(panely[name]);if(panel)panel.classList.add('aktivne')}
$$('.zalozky-panelu button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('#pridatHosta').onclick=()=>openGuest();$('#hladanieHosta').oninput=renderGuests;$('#filterHosti').onchange=renderGuests;
$('#resetovatPlan').onclick=e=>{e.preventDefault();showDialog($('#dialogResetovania'))};
function aktualizujPrepinacEditovania(){const prepinac=$('#prepinacEditovania');prepinac.textContent=nastaveniePlochy.editovatelnyRezim?'Vypnúť editovateľný režim':'Zapnúť editovateľný režim';prepinac.setAttribute('aria-pressed',String(nastaveniePlochy.editovatelnyRezim))}
$('#prepinacEditovania').onclick=e=>{e.preventDefault();nastaveniePlochy.editovatelnyRezim=!nastaveniePlochy.editovatelnyRezim;aktualizujPrepinacEditovania();renderItems();toast(nastaveniePlochy.editovatelnyRezim?'Editovateľný režim je zapnutý':'Editovateľný režim je vypnutý')};
aktualizujPrepinacEditovania();
$('#potvrditResetovanie').onclick=()=>{snapshot();state=vytvorStavSPredvolenymiPrvkami();selectedItem='';editingGuest='';editingItem='';localStorage.setItem('wedding-planner-v1',JSON.stringify(state));closeDialog($('#dialogResetovania'));renderAll();openTab('overview');toast('Plán sály bol obnovený z predvoleného rozloženia')};
function renderEvent(){$$('[data-event]').forEach(e=>e.value=state.wedding[e.dataset.event]||'')};$$('[data-event]').forEach(e=>e.addEventListener('input',()=>{state.wedding[e.dataset.event]=e.value;changed()}));
function zoom(delta,cx,cy){const old=state.settings.zoom,n=Math.min(1.8,Math.max(.35,old+delta)),r=els.viewport.getBoundingClientRect(),x=cx??r.left+r.width/2,y=cy??r.top+r.height/2,wx=(x-r.left-state.settings.panX)/old,wy=(y-r.top-state.settings.panY)/old;state.settings.zoom=n;state.settings.panX=x-r.left-wx*n;state.settings.panY=y-r.top-wy*n;setTransform();changed()}
els.viewport.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?-.07:.07,e.clientX,e.clientY)},{passive:false});
els.viewport.addEventListener('pointerdown',e=>{
  if(e.target.closest('.prvok-podorysu')||(e.button!==0&&e.button!==1))return;
  e.preventDefault();
  if(selectedItem){selectedItem='';renderItems();renderTableDetail()}
  const sx=e.clientX,sy=e.clientY,px=state.settings.panX,py=state.settings.panY;
  els.viewport.classList.add('prebieha-posun');
  els.viewport.setPointerCapture(e.pointerId);
  const mv=ev=>{state.settings.panX=px+ev.clientX-sx;state.settings.panY=py+ev.clientY-sy;setTransform()};
  const finish=()=>{els.viewport.classList.remove('prebieha-posun');els.viewport.removeEventListener('pointermove',mv);els.viewport.removeEventListener('pointerup',finish);els.viewport.removeEventListener('pointercancel',finish);changed()};
  els.viewport.addEventListener('pointermove',mv);els.viewport.addEventListener('pointerup',finish);els.viewport.addEventListener('pointercancel',finish)
});
document.addEventListener('keydown',e=>{if(e.code==='Space')space=true;const isDelete=e.key==='Delete'||e.key==='Del'||e.keyCode===46;if(!isDelete||!selectedItem)return;const target=e.target;if(target.matches('input, textarea, select')||target.isContentEditable||document.querySelector('dialog[open]'))return;e.preventDefault();removeObject(selectedItem)});document.addEventListener('keyup',e=>{if(e.code==='Space')space=false});
$('#exportovatPlan').onclick=()=>download(JSON.stringify(state,null,2),`svadobny-plan-${state.wedding.date||new Date().toISOString().slice(0,10)}.json`);$('#importovatPlan').onclick=()=>$('#vstupSuboru').click();$('#vstupSuboru').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(!validProject(s))throw Error();snapshot();state=s;renderAll();changed();toast('Projekt bol importovaný')}catch{toast('Neplatný súbor projektu')}e.target.value=''};
function vytvorPdfElement(tag,trieda='',text=''){const element=document.createElement(tag);if(trieda)element.className=trieda;if(text!=='')element.textContent=text;return element}
function formatujDatumPdf(hodnota){const zhoda=String(hodnota||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return zhoda?`${zhoda[3]}.${zhoda[2]}.${zhoda[1]}`:'Dátum neuvedený'}
function pridajPdfHlavicku(strana){const hlavicka=vytvorPdfElement('div','pdf-hlavicka'),logo=document.createElement('img'),nazov=vytvorPdfElement('strong','pdf-nazov-podujatia',state.wedding.eventName||'Názov podujatia'),datum=vytvorPdfElement('strong','pdf-termin',`Termín: ${formatujDatumPdf(state.wedding.date)}`);logo.src='assets/bukovina.png';logo.alt='Bukovina';hlavicka.append(logo,nazov,datum);strana.append(hlavicka)}
function pridajPdfCisloStrany(strana,cislo,celkom){strana.append(vytvorPdfElement('div','pdf-cislo-strany',`Strana ${cislo} z ${celkom}`))}
function vytvorPdfRiadokHosta(cislo,g){const riadok=vytvorPdfElement('div','pdf-riadok-hosta'),nazov=vytvorPdfElement('b','',`Miesto ${cislo}: `);riadok.append(nazov);if(!g){riadok.append(document.createTextNode('Voľné'));return riadok}riadok.append(document.createTextNode(`${g.firstName} ${g.lastName} · ${g.personType==='child'?'Dieťa':'Dospelý'}`));const detaily=[];if(g.allergies?.length)detaily.push(`Alergie: ${g.allergies.join(', ')}`);if(g.note?.trim())detaily.push(`Poznámka: ${g.note.trim()}`);if(detaily.length)riadok.append(vytvorPdfElement('span','pdf-detail-hosta',detaily.join(' · ')));return riadok}
function pridajPdfUdaj(rodic,nazov,hodnota){const blok=vytvorPdfElement('div','pdf-udaj'),popis=vytvorPdfElement('small','',nazov),obsah=vytvorPdfElement('div','',hodnota||'—');blok.append(popis,obsah);rodic.append(blok)}
function vytvorPdfStranuPodorysu(canvas,celkom){const strana=vytvorPdfElement('section','pdf-strana pdf-podorys');pridajPdfHlavicku(strana);const obrazok=vytvorPdfElement('div','pdf-obrazok-saly');obrazok.append(canvas);strana.append(obrazok);pridajPdfCisloStrany(strana,1,celkom);return strana}
function rozdelPdfPrehlad(){const limit=36,strany=[[]];let pouzite=0;const novaStrana=()=>{strany.push([]);pouzite=0},pridaj=(zaznam,vaha)=>{if(pouzite&&pouzite+vaha>limit)novaStrana();strany[strany.length-1].push(zaznam);pouzite+=vaha};state.items.filter(isTable).slice().sort((a,b)=>(a.number||0)-(b.number||0)).forEach(stol=>{let od=1;while(od<=stol.seats){if(pouzite&&limit-pouzite<6)novaStrana();let po=od-1,vaha=4;while(po<stol.seats){const host=state.guests.find(g=>g.tableId===stol.id&&+g.seatNumber===po+1),riadok=1+(host&&(host.allergies?.length||host.note?.trim())?1:0);if(po>=od&&pouzite+vaha+riadok>limit)break;vaha+=riadok;po++}pridaj({typ:'stol',stol,od,po},vaha);od=po+1;if(od<=stol.seats)novaStrana()}});const bezMiesta=state.guests.filter(g=>!g.tableId);for(let od=0;od<bezMiesta.length;){if(pouzite&&limit-pouzite<5)novaStrana();let po=od,vaha=3;while(po<bezMiesta.length){const g=bezMiesta[po],riadok=1+(g.allergies?.length||g.note?.trim()?1:0);if(po>od&&pouzite+vaha+riadok>limit)break;vaha+=riadok;po++}pridaj({typ:'bez-miesta',hostia:bezMiesta.slice(od,po),pokracovanie:od>0},vaha);od=po;if(od<bezMiesta.length)novaStrana()}return strany.filter(strana=>strana.length)}
function vytvorPdfStranuPrehladu(obsah,cislo,celkom){const strana=vytvorPdfElement('section','pdf-strana');pridajPdfHlavicku(strana);const report=vytvorPdfElement('div','pdf-prehlad'),hlavny=vytvorPdfElement('div','pdf-hlavne-udaje'),bok=vytvorPdfElement('aside','pdf-bocne-udaje'),zoznam=vytvorPdfElement('div','pdf-zoznam-stolov');obsah.forEach(zaznam=>{if(zaznam.typ==='stol'){const stol=zaznam.stol,blok=vytvorPdfElement('section','pdf-stol'),nadpis=vytvorPdfElement('h3','',`${stol.name}${stol.number?` · číslo ${stol.number}`:''}`),obsadene=state.guests.filter(g=>g.tableId===stol.id).length,popis=vytvorPdfElement('p','',`${obsadene} z ${stol.seats} miest obsadených${stol.note?.trim()?` · Poznámka stola: ${stol.note.trim()}`:''}`);blok.append(nadpis,popis);for(let miesto=zaznam.od;miesto<=zaznam.po;miesto++){const host=state.guests.find(g=>g.tableId===stol.id&&+g.seatNumber===miesto);blok.append(vytvorPdfRiadokHosta(miesto,host))}zoznam.append(blok)}else{const blok=vytvorPdfElement('section','pdf-bez-miesta');blok.append(vytvorPdfElement('h3','',`Hostia bez prideleného miesta${zaznam.pokracovanie?' · pokračovanie':''}`));zaznam.hostia.forEach(g=>{const riadok=vytvorPdfElement('div','pdf-riadok-hosta'),meno=vytvorPdfElement('b','',[g.firstName,g.lastName].filter(Boolean).join(' ')),detaily=[];if(g.allergies?.length)detaily.push(`Alergie: ${g.allergies.join(', ')}`);if(g.note?.trim())detaily.push(`Poznámka: ${g.note.trim()}`);riadok.append(meno);if(detaily.length)riadok.append(vytvorPdfElement('span','pdf-detail-hosta',detaily.join(' · ')));blok.append(riadok)});zoznam.append(blok)}});hlavny.append(zoznam);const stoly=state.items.filter(isTable),kapacita=stoly.reduce((s,t)=>s+t.seats,0),usadeni=state.guests.filter(g=>g.tableId).length,suhrnKarta=vytvorPdfElement('section','pdf-karta'),suhrn=vytvorPdfElement('div','pdf-sumar');suhrnKarta.append(vytvorPdfElement('h2','','Súhrn'));[['Hostia',state.guests.length],['Stoly',stoly.length],['Voľné miesta',Math.max(0,kapacita-usadeni)],['Alergie',state.guests.filter(g=>g.allergies?.length).length]].forEach(([nazov,hodnota])=>{const udaj=vytvorPdfElement('div'),popis=vytvorPdfElement('small','',nazov),hodnotaElement=vytvorPdfElement('b','',String(hodnota));udaj.append(popis,hodnotaElement);suhrn.append(udaj)});suhrnKarta.append(suhrn);const podujatie=vytvorPdfElement('section','pdf-karta pdf-podujatie');podujatie.append(vytvorPdfElement('h2','','Podujatie'));pridajPdfUdaj(podujatie,'Názov podujatia',state.wedding.eventName);pridajPdfUdaj(podujatie,'Dátum',formatujDatumPdf(state.wedding.date));pridajPdfUdaj(podujatie,'Kontaktná osoba',state.wedding.contactName);pridajPdfUdaj(podujatie,'Telefón',state.wedding.phone);pridajPdfUdaj(podujatie,'E-mail',state.wedding.email);pridajPdfUdaj(podujatie,'Popis a poznámka',state.wedding.note);bok.append(suhrnKarta,podujatie);report.append(hlavny,bok);strana.append(report);pridajPdfCisloStrany(strana,cislo,celkom);return strana}
function pockajNaPdfObrazky(rodic){return Promise.all([...rodic.querySelectorAll('img')].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve})))}
async function exportPdf(){if(!window.html2canvas||!window.jspdf){toast('Nástroje PDF sa nepodarilo načítať');return}const button=$('#vytvoritPdf'),oldText=button.textContent,oldSelected=selectedItem,oldTransform=els.world.style.transform,pdfStrany=[];button.disabled=true;button.textContent='Vytváram PDF…';toast('Pripravujem PDF plán…');try{selectedItem='';renderItems();els.world.style.transform='none';els.world.classList.add('pdf-obrysy');if(document.fonts&&document.fonts.ready)await document.fonts.ready;const sala=await window.html2canvas(els.world,{backgroundColor:'#fff',scale:1,useCORS:true,logging:false,width:1800,height:1200}),obsahy=rozdelPdfPrehlad(),celkom=1+obsahy.length,prva=vytvorPdfStranuPodorysu(sala,celkom);pdfStrany.push(prva,...obsahy.map((obsah,index)=>vytvorPdfStranuPrehladu(obsah,index+2,celkom)));document.body.append(...pdfStrany);await Promise.all(pdfStrany.map(pockajNaPdfObrazky));const platna=[];for(const strana of pdfStrany)platna.push(await window.html2canvas(strana,{backgroundColor:'#fff',scale:1.4,useCORS:true,logging:false,width:1400,height:990}));const{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),pageW=pdf.internal.pageSize.getWidth(),pageH=pdf.internal.pageSize.getHeight();platna.forEach((platno,index)=>{if(index)pdf.addPage('a4','landscape');pdf.addImage(platno.toDataURL('image/jpeg',.94),'JPEG',0,0,pageW,pageH,undefined,'FAST')});pdf.save(`svadobny-plan-${state.wedding.date||new Date().toISOString().slice(0,10)}.pdf`);toast(`PDF bolo vytvorené (${celkom} strán)`)}catch(error){console.error(error);toast('PDF sa nepodarilo vytvoriť')}finally{pdfStrany.forEach(strana=>strana.remove());els.world.classList.remove('pdf-obrysy');els.world.style.transform=oldTransform;selectedItem=oldSelected;renderItems();button.disabled=false;button.textContent=oldText}}
$('#vytvoritPdf').onclick=exportPdf;
$('#odoslatPlan').onclick=()=>{const cap=state.items.filter(isTable).reduce((a,t)=>a+t.seats,0),seated=state.guests.filter(g=>g.tableId).length,lines=[['Hostia',state.guests.length],['Stoly',state.items.filter(isTable).length],['Voľné miesta',cap-seated],['Hostia bez miesta',state.guests.length-seated],['Hostia s alergiou',state.guests.filter(g=>g.allergies.length).length],['Poznámka',state.wedding.note||'—'],['Posledné uloženie',new Date(state.meta.updatedAt).toLocaleString('sk-SK')]];const c=$('#obsahRekapitulacie');c.replaceChildren(...lines.map(([a,b])=>{const p=document.createElement('p'),x=document.createElement('b');x.textContent=a+': ';p.append(x,document.createTextNode(b));return p}));showDialog($('#dialogRekapitulacie'))};$('#potvrditOdoslanie').onclick=()=>{state.meta.submittedAt=new Date().toISOString();save();const stamp=state.meta.submittedAt.replace(/:/g,'-');download(JSON.stringify(state,null,2),`submissions/svadobny-plan-${stamp}.json`);closeDialog($('#dialogRekapitulacie'));toast('Finálna verzia bola uložená')};
window.addEventListener('beforeunload',save);renderLibrary();renderAll();
