import{TYPES,PERSON_ICONS,ALLERGIES,initialState,load,validProject,download}from'./state.js';
let state=load(),selectedItem='',editingGuest='',editingItem='',saveTimer,drag=null,space=false,history=[],future=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],els={world:$('#world'),items:$('#items'),viewport:$('#viewport'),library:$('#library'),guestList:$('#guestList'),stats:$('#stats'),tableDetail:$('#tableDetail')};
const uid=()=>globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)}),isTable=i=>i&&i.type.includes('table'),esc=s=>String(s??'');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function formDataObject(form){const result={};new FormData(form).forEach((value,key)=>{result[key]=value});return result}
function showDialog(dialog){if(typeof dialog.showModal==='function')dialog.showModal();else{dialog.setAttribute('open','');dialog.classList.add('dialog-fallback')}}
function closeDialog(dialog){if(typeof dialog.close==='function')dialog.close();else{dialog.removeAttribute('open');dialog.classList.remove('dialog-fallback')}}
function createVisualIcon(value,className=''){const icon=String(value||'');if(icon.startsWith('fa_')){const element=document.createElement('i');element.className=`fa-sharp fa-light fa-${icon.slice(3).replace(/_/g,'-')} visual-icon ${className}`;element.setAttribute('aria-hidden','true');return element}if(icon.toLowerCase().endsWith('.svg')){const image=document.createElement('img');image.className=`visual-icon svg-icon ${className}`;image.src=icon.startsWith('assets/')?icon:`assets/${icon}`;image.alt='';image.draggable=false;return image}const fallback=document.createElement('span');fallback.className=`visual-icon ${className}`;fallback.textContent=icon;return fallback}
function fillItemVisual(container,icon,label,visibility={icon:true,text:true}){const nodes=[],showIcon=visibility.icon!==false,showText=visibility.text!==false;container.classList.toggle('icon-only',showIcon&&!showText);container.classList.toggle('text-only',!showIcon&&showText);if(showIcon)nodes.push(createVisualIcon(icon,'item-visual-icon'));if(showText){const text=document.createElement('span');text.className='object-label';text.textContent=label;nodes.push(text)}container.replaceChildren(...nodes)}
function shapeClass(def){return `shape-${def?.[6]?.shape||'sharp'}`}
window.closePlannerDialog=closeDialog;
function snapshot(){history.push(JSON.stringify(state));if(history.length>40)history.shift();future=[]}
function changed(){state.meta.updatedAt=new Date().toISOString();clearTimeout(saveTimer);saveTimer=setTimeout(save,1000);renderStats()}
function save(){try{localStorage.setItem('wedding-planner-v1',JSON.stringify(state))}catch(error){console.error('Projekt sa nepodarilo uložiť.',error)}}
function renderAll(){setTransform();renderItems();renderGuests();renderStats();renderEvent();if(selectedItem)renderTableDetail()}
function setTransform(){els.world.style.transform=`translate(${state.settings.panX}px,${state.settings.panY}px) scale(${state.settings.zoom})`}
function renderLibrary(){TYPES.forEach(([type,name,icon])=>{const d=document.createElement('div'),label=document.createElement('span'),iconWrap=document.createElement('span');d.className='lib-item';d.dataset.type=type;iconWrap.className='lib-icon';iconWrap.append(createVisualIcon(icon));label.textContent=name;d.append(iconWrap,label);d.addEventListener('pointerdown',libraryPointer);els.library.append(d)})}
els.library.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<=Math.abs(e.deltaX))return;e.preventDefault();els.library.scrollLeft+=e.deltaY},{passive:false});
function addItem(type,x,y){snapshot();const def=TYPES.find(t=>t[0]===type),n=state.items.filter(i=>i.type===type).length+1;state.items.push({id:uid(),type,name:def[1]+' '+n,x,y,width:def[3],height:def[4],rotation:0,number:n,seats:def[5],note:'',locked:false});selectedItem=state.items[state.items.length-1].id;renderItems();changed()}
function libraryPointer(e){const card=e.currentTarget,type=card.dataset.type,def=TYPES.find(t=>t[0]===type),startX=e.clientX,startY=e.clientY,preview=document.createElement('div'),shape=document.createElement('div');preview.className=`drag-preview ${type} ${shapeClass(def)}`;preview.style.width=Math.max(60,Math.min(160,def[3]*.55))+'px';preview.style.height=Math.max(50,Math.min(110,def[4]*.55))+'px';shape.className='object-shape';fillItemVisual(shape,def[2],def[1],{icon:true,text:false});preview.append(shape);document.body.append(preview);drag={library:type};card.classList.add('dragging');card.setPointerCapture(e.pointerId);const move=ev=>{const distance=Math.hypot(ev.clientX-startX,ev.clientY-startY);preview.style.left=ev.clientX+'px';preview.style.top=ev.clientY+'px';if(distance>5)preview.classList.add('visible')};const cleanup=()=>{card.classList.remove('dragging');preview.remove();drag=null;card.removeEventListener('pointermove',move);card.removeEventListener('pointerup',up);card.removeEventListener('pointercancel',cancel)};const up=ev=>{const r=els.viewport.getBoundingClientRect(),distance=Math.hypot(ev.clientX-startX,ev.clientY-startY),target=document.elementFromPoint(ev.clientX,ev.clientY),overLibrary=target&&target.closest('.library-wrap');if(distance>8&&!overLibrary&&ev.clientX>r.left&&ev.clientX<r.right&&ev.clientY>r.top&&ev.clientY<r.bottom){const p=screenToWorld(ev.clientX,ev.clientY);addItem(type,p.x-def[3]/2,p.y-def[4]/2)}cleanup()};const cancel=()=>cleanup();card.addEventListener('pointermove',move);card.addEventListener('pointerup',up);card.addEventListener('pointercancel',cancel)}
function screenToWorld(x,y){const r=els.viewport.getBoundingClientRect(),z=state.settings.zoom;return{x:(x-r.left-state.settings.panX)/z,y:(y-r.top-state.settings.panY)/z}}
function renderItems(){els.items.replaceChildren();state.items.forEach(i=>{const d=document.createElement('div'),def=TYPES.find(t=>t[0]===i.type);d.className=`floor-item ${i.type} ${shapeClass(def)}${i.id===selectedItem?' selected':''}${i.locked?' locked':''}`;d.dataset.id=i.id;Object.assign(d.style,{left:i.x+'px',top:i.y+'px',width:i.width+'px',height:i.height+'px',transform:`rotate(${Number(i.rotation)||0}deg)`});const sh=document.createElement('div');sh.className='object-shape';fillItemVisual(sh,def?def[2]:'',i.name,def&&def[6]?def[6]:{icon:true,text:true});d.append(sh);if(isTable(i))renderSeats(d,i);if(i.id===selectedItem){const actions=document.createElement('div');actions.className='object-actions';actions.addEventListener('pointerdown',e=>e.stopPropagation());const edit=document.createElement('button');edit.type='button';edit.append(createVisualIcon('fa_pen'));edit.title='Upraviť objekt';edit.onclick=e=>{e.stopPropagation();openItem(i.id)};const duplicate=document.createElement('button');duplicate.type='button';duplicate.append(createVisualIcon('fa_copy'));duplicate.title='Duplikovať objekt';duplicate.onclick=e=>{e.stopPropagation();duplicateObject(i.id)};const remove=document.createElement('button');remove.type='button';remove.append(createVisualIcon('fa_xmark'));remove.title='Odstrániť objekt';remove.className='remove';remove.onclick=e=>{e.stopPropagation();removeObject(i.id)};actions.append(edit,duplicate,remove);d.append(actions)}d.addEventListener('pointerdown',itemPointer);d.addEventListener('dblclick',()=>openItem(i.id));d.addEventListener('click',e=>{e.stopPropagation();selectedItem=i.id;renderItems();if(isTable(i)){openTab('table');renderTableDetail()}});els.items.append(d)})}
function renderSeats(parent,item){for(let n=1;n<=item.seats;n++){const s=document.createElement('button'),a=(n/item.seats)*Math.PI*2-Math.PI/2,rx=item.width/2+25,ry=item.height/2+25,g=state.guests.find(x=>x.tableId===item.id&&+x.seatNumber===n);s.className='seat'+(g?' occupied':'')+(g?.allergies.length?' has-allergy':'')+(g?.personType==='child'?' child':'');if(item.type==='head-table'){s.style.left=item.width*n/(item.seats+1)+'px';s.style.top='-24px'}else{s.style.left=item.width/2+Math.cos(a)*rx+'px';s.style.top=item.height/2+Math.sin(a)*ry+'px'}s.textContent=g?(g.firstName[0]+g.lastName[0]):n;if(g?.personType==='child')s.append(createVisualIcon(PERSON_ICONS.child,'seat-person-icon'));s.title=g?g.firstName+' '+g.lastName:`Miesto ${n}`;s.addEventListener('pointerdown',e=>e.stopPropagation());s.addEventListener('click',e=>{e.stopPropagation();selectedItem=item.id;openTab('table');renderTableDetail(n)});s.addEventListener('dragover',e=>e.preventDefault());s.addEventListener('drop',e=>{e.preventDefault();assignGuest(e.dataTransfer.getData('text/guest'),item.id,n)});parent.append(s)}}
function itemPointer(e){if(e.button!==0)return;const i=state.items.find(x=>x.id===e.currentTarget.dataset.id);if(!i||i.locked)return;e.stopPropagation();snapshot();const p=screenToWorld(e.clientX,e.clientY),ox=i.x-p.x,oy=i.y-p.y,node=e.currentTarget;node.setPointerCapture(e.pointerId);const move=ev=>{const q=screenToWorld(ev.clientX,ev.clientY);i.x=Math.round(q.x+ox);i.y=Math.round(q.y+oy);node.style.left=i.x+'px';node.style.top=i.y+'px'};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);changed()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up)}
function renderStats(){const tables=state.items.filter(isTable),capacity=tables.reduce((a,t)=>a+t.seats,0),seated=state.guests.filter(g=>g.tableId).length,vals=[['Hostia',state.guests.length],['Dospelí',state.guests.filter(g=>g.personType==='adult').length],['Deti',state.guests.filter(g=>g.personType==='child').length],['Stoly',tables.length],['Obsadené',seated],['Voľné miesta',Math.max(0,capacity-seated)],['Alergie',state.guests.filter(g=>g.allergies.length).length],['Bez miesta',state.guests.length-seated]];els.stats.replaceChildren(...vals.map(([l,v])=>{const d=document.createElement('div');d.className='stat';const s=document.createElement('small'),b=document.createElement('b');s.textContent=l;b.textContent=v;d.append(s,b);return d}))}
function renderGuests(){const q=$('#guestSearch').value.toLowerCase(),f=$('#guestFilter').value;els.guestList.replaceChildren();state.guests.filter(g=>{const m=(g.firstName+' '+g.lastName).toLowerCase().includes(q);return m&&(f==='all'||f==='unseated'&&!g.tableId||f==='allergy'&&g.allergies.length||f==='child'&&g.personType==='child')}).forEach(g=>{const t=state.items.find(i=>i.id===g.tableId),d=document.createElement('div');d.className='guest-row';d.draggable=true;d.addEventListener('dragstart',e=>e.dataTransfer.setData('text/guest',g.id));const av=document.createElement('div');av.className='avatar';av.append(createVisualIcon(PERSON_ICONS[g.personType]||PERSON_ICONS.adult));const info=document.createElement('div'),b=document.createElement('b'),sm=document.createElement('small');b.textContent=g.firstName+' '+g.lastName;sm.textContent=(g.personType==='child'?'Dieťa':'Dospelý')+' · '+(t?`${t.name}, miesto ${g.seatNumber}`:'Bez miesta');info.append(b,sm);g.allergies.forEach(a=>{const x=document.createElement('span');x.className='tag';x.textContent=a;info.append(x)});const acts=document.createElement('div');acts.className='guest-actions';const edit=document.createElement('button');edit.append(createVisualIcon('fa_pen'));edit.title='Upraviť';edit.onclick=()=>openGuest(g.id);const del=document.createElement('button');del.append(createVisualIcon('fa_xmark'));del.title='Odstrániť';del.onclick=()=>{if(confirm('Odstrániť hosťa?')){snapshot();state.guests=state.guests.filter(x=>x.id!==g.id);renderAll();changed()}};acts.append(edit,del);d.append(av,info,acts);els.guestList.append(d)})}
function assignGuest(gid,tid,seat){const g=state.guests.find(x=>x.id===gid);if(!g)return;const occupied=state.guests.find(x=>x.tableId===tid&&+x.seatNumber===+seat&&x.id!==gid);if(occupied&&!confirm(`Miesto je obsadené hosťom ${occupied.firstName}. Vymeniť?`))return;snapshot();if(occupied){occupied.tableId='';occupied.seatNumber=null}g.tableId=tid;g.seatNumber=seat;renderAll();changed()}
function renderTableDetail(focusSeat){const t=state.items.find(i=>i.id===selectedItem);if(!isTable(t)){els.tableDetail.innerHTML='<div class="empty"><b>Vyberte stôl</b></div>';return}els.tableDetail.replaceChildren();const head=document.createElement('div');head.className='section-head';const h=document.createElement('h2');h.textContent=t.name;const edit=document.createElement('button');edit.textContent='Upraviť stôl';edit.onclick=()=>openItem(t.id);head.append(h,edit);const map=document.createElement('div');map.className='seat-map '+(t.type==='round-table'?'':'rect')+(t.type==='head-table'?' head':'');const table=document.createElement('div');table.className='table-preview';table.textContent=t.number?`Stôl ${t.number}`:t.name;map.append(table);for(let n=1;n<=t.seats;n++){const a=n/t.seats*Math.PI*2-Math.PI/2,g=state.guests.find(x=>x.tableId===t.id&&+x.seatNumber===n),s=document.createElement('button');s.className='detail-seat'+(g?' occupied':'');if(t.type==='head-table'){s.style.left=8+n/(t.seats+1)*84+'%';s.style.top='20%'}else{s.style.left=50+Math.cos(a)*42+'%';s.style.top=50+Math.sin(a)*42+'%'}s.textContent=g?g.firstName:n;s.title=g?`${g.firstName} ${g.lastName}`:`Miesto ${n}`;s.onclick=()=>seatEditor(t,n,g);s.ondragover=e=>e.preventDefault();s.ondrop=e=>assignGuest(e.dataTransfer.getData('text/guest'),t.id,n);map.append(s)}els.tableDetail.append(head,map);if(focusSeat){const g=state.guests.find(x=>x.tableId===t.id&&+x.seatNumber===focusSeat);seatEditor(t,focusSeat,g)}}
function seatEditor(t,n,g){let box=$('#seatEditor');if(box)box.remove();box=document.createElement('div');box.id='seatEditor';const label=document.createElement('b');label.textContent=`Miesto ${n}`;const help=document.createElement('small');help.textContent=g?'Priradený hosť':'Vyberte hosťa zo zoznamu alebo vytvorte nového';const sel=document.createElement('select');const empty=document.createElement('option');empty.value='';empty.textContent='— Voľné miesto —';sel.append(empty);state.guests.filter(x=>!x.tableId||x.id===g?.id).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.firstName+' '+x.lastName;o.selected=x.id===g?.id;sel.append(o)});sel.onchange=()=>sel.value?assignGuest(sel.value,t.id,n):(g&&(snapshot(),g.tableId='',g.seatNumber=null,renderAll(),changed()));const add=document.createElement('button');add.type='button';add.className='primary';add.textContent='＋ Pridať nového hosťa';add.onclick=()=>openGuest('',{tableId:t.id,seatNumber:n});box.append(label,help,sel,add);els.tableDetail.append(box)}
function openGuest(id='',assignment=null){editingGuest=id;const g=state.guests.find(x=>x.id===id)||{firstName:'',lastName:'',personType:'adult',childAge:'',tableId:assignment?assignment.tableId:'',seatNumber:assignment?assignment.seatNumber:'',allergies:[],note:''};$('#guestDialogTitle').textContent=id?'Upraviť hosťa':'Pridať hosťa';const f=$('#guestForm');['firstName','lastName','personType','childAge','seatNumber','note'].forEach(k=>f.elements[k].value=g[k]??'');const ts=f.elements.tableId;ts.replaceChildren(new Option('Bez miesta',''),...state.items.filter(isTable).map(t=>new Option(t.name,t.id)));ts.value=g.tableId||'';$('#allergyChoices').replaceChildren(...ALLERGIES.map(a=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.value=a;c.checked=g.allergies.includes(a);l.append(c,document.createTextNode(a));return l}));showDialog($('#guestDialog'))}
$('#guestForm').addEventListener('submit',e=>{e.preventDefault();const obj=formDataObject(e.currentTarget);if(!obj.firstName.trim()||!obj.lastName.trim())return;const seat=+obj.seatNumber||null;if(obj.tableId&&seat){const t=state.items.find(x=>x.id===obj.tableId);if(!t||seat>t.seats)return toast('Neplatné číslo miesta');const occ=state.guests.find(x=>x.tableId===obj.tableId&&+x.seatNumber===seat&&x.id!==editingGuest);if(occ)return toast('Toto miesto je už obsadené')}snapshot();const old=state.guests.find(x=>x.id===editingGuest);const g={...(old||{id:uid(),color:'#d98a8f'}),...obj,childAge:obj.personType==='child'?+obj.childAge||'':'',seatNumber:seat,allergies:$$('#allergyChoices input:checked').map(x=>x.value)};delete g.menu;delete g.companion;delete g.group;delete g.rsvp;if(old){Object.keys(old).forEach(key=>delete old[key]);Object.assign(old,g)}else state.guests.push(g);closeDialog($('#guestDialog'));renderAll();changed()});
function openItem(id){editingItem=id;const i=state.items.find(x=>x.id===id),f=$('#itemForm');['name','number','width','height','rotation','seats','note'].forEach(k=>f.elements[k].value=i[k]??'');f.elements.seats.disabled=!isTable(i);$$('.table-only').forEach(x=>x.style.display=isTable(i)?'block':'none');$('#lockItem').textContent=i.locked?'Odomknúť':'Uzamknúť';showDialog($('#itemDialog'))}
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const i=state.items.find(x=>x.id===editingItem);if(!i)return;const f=e.currentTarget,d=formDataObject(f);if(typeof f.reportValidity==='function'&&!f.reportValidity())return;snapshot();Object.assign(i,{name:String(d.name||i.name).slice(0,80),number:Number(d.number)||0,width:Math.min(800,Math.max(40,Number(d.width)||i.width)),height:Math.min(800,Math.max(40,Number(d.height)||i.height)),rotation:Number(d.rotation)||0,seats:isTable(i)?Math.min(30,Math.max(1,Number(d.seats)||1)):0,note:String(d.note||'').slice(0,500)});closeDialog($('#itemDialog'));renderAll();changed();toast('Objekt bol uložený')});
function removeObject(id){if(!state.items.some(x=>x.id===id))return;snapshot();state.guests.filter(g=>g.tableId===id).forEach(g=>{g.tableId='';g.seatNumber=null});state.items=state.items.filter(x=>x.id!==id);selectedItem='';editingItem='';if($('#itemDialog').open)closeDialog($('#itemDialog'));renderAll();renderTableDetail();changed()}
function duplicateObject(id){const i=state.items.find(x=>x.id===id);if(!i)return;snapshot();const c={...i,id:uid(),name:i.name+' – kópia',x:i.x+35,y:i.y+35,number:state.items.filter(x=>x.type===i.type).length+1,locked:false};state.items.push(c);if($('#itemDialog').open)closeDialog($('#itemDialog'));selectedItem=c.id;renderAll();changed();toast('Objekt bol duplikovaný')}
$('#deleteItem').onclick=()=>removeObject(editingItem);$('#duplicateItem').onclick=()=>duplicateObject(editingItem);$('#lockItem').onclick=()=>{const i=state.items.find(x=>x.id===editingItem);snapshot();i.locked=!i.locked;closeDialog($('#itemDialog'));renderAll();changed()};
function openTab(name){$$('.side-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.remove('active'));$('#'+name+'Tab').classList.add('active')}
$$('.side-tabs button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('#addGuest').onclick=()=>openGuest();$('#guestSearch').oninput=renderGuests;$('#guestFilter').onchange=renderGuests;
$('#resetPlan').onclick=e=>{e.preventDefault();showDialog($('#resetDialog'))};
$('#confirmReset').onclick=()=>{snapshot();state=initialState();selectedItem='';editingGuest='';editingItem='';localStorage.setItem('wedding-planner-v1',JSON.stringify(state));closeDialog($('#resetDialog'));renderAll();openTab('overview');toast('Plán sály bol obnovený')};
function renderEvent(){$$('[data-event]').forEach(e=>e.value=state.wedding[e.dataset.event]||'')};$$('[data-event]').forEach(e=>e.addEventListener('input',()=>{state.wedding[e.dataset.event]=e.value;changed()}));
function zoom(delta,cx,cy){const old=state.settings.zoom,n=Math.min(1.8,Math.max(.35,old+delta)),r=els.viewport.getBoundingClientRect(),x=cx??r.left+r.width/2,y=cy??r.top+r.height/2,wx=(x-r.left-state.settings.panX)/old,wy=(y-r.top-state.settings.panY)/old;state.settings.zoom=n;state.settings.panX=x-r.left-wx*n;state.settings.panY=y-r.top-wy*n;setTransform();changed()}
els.viewport.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?-.07:.07,e.clientX,e.clientY)},{passive:false});
els.viewport.addEventListener('pointerdown',e=>{
  if(e.target.closest('.floor-item')||(e.button!==0&&e.button!==1))return;
  e.preventDefault();
  if(selectedItem){selectedItem='';renderItems();renderTableDetail()}
  const sx=e.clientX,sy=e.clientY,px=state.settings.panX,py=state.settings.panY;
  els.viewport.classList.add('is-panning');
  els.viewport.setPointerCapture(e.pointerId);
  const mv=ev=>{state.settings.panX=px+ev.clientX-sx;state.settings.panY=py+ev.clientY-sy;setTransform()};
  const finish=()=>{els.viewport.classList.remove('is-panning');els.viewport.removeEventListener('pointermove',mv);els.viewport.removeEventListener('pointerup',finish);els.viewport.removeEventListener('pointercancel',finish);changed()};
  els.viewport.addEventListener('pointermove',mv);els.viewport.addEventListener('pointerup',finish);els.viewport.addEventListener('pointercancel',finish)
});
document.addEventListener('keydown',e=>{if(e.code==='Space')space=true;const isDelete=e.key==='Delete'||e.key==='Del'||e.keyCode===46;if(!isDelete||!selectedItem)return;const target=e.target;if(target.matches('input, textarea, select')||target.isContentEditable||document.querySelector('dialog[open]'))return;e.preventDefault();removeObject(selectedItem)});document.addEventListener('keyup',e=>{if(e.code==='Space')space=false});
$('#exportBtn').onclick=()=>download(JSON.stringify(state,null,2),`svadobny-plan-${state.wedding.date||new Date().toISOString().slice(0,10)}.json`);$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(!validProject(s))throw Error();snapshot();state=s;renderAll();changed();toast('Projekt bol importovaný')}catch{toast('Neplatný súbor projektu')}e.target.value=''};
async function exportPdf(){if(!window.html2canvas||!window.jspdf){toast('Nástroje PDF sa nepodarilo načítať');return}const button=$('#pdfBtn'),oldText=button.textContent,oldSelected=selectedItem,oldTransform=els.world.style.transform;button.disabled=true;button.textContent='Vytváram PDF…';toast('Pripravujem pôdorys do PDF…');try{selectedItem='';renderItems();els.world.style.transform='none';if(document.fonts&&document.fonts.ready)await document.fonts.ready;const canvas=await window.html2canvas(els.world,{backgroundColor:'#fffdf9',scale:1,useCORS:true,logging:false,width:1800,height:1200});const{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),pageW=pdf.internal.pageSize.getWidth(),pageH=pdf.internal.pageSize.getHeight(),margin=10,top=24,maxW=pageW-margin*2,maxH=pageH-top-margin,ratio=Math.min(maxW/canvas.width,maxH/canvas.height),w=canvas.width*ratio,h=canvas.height*ratio,x=(pageW-w)/2;pdf.setTextColor(62,57,53);pdf.setFontSize(17);pdf.text('Svadobný plán',margin,12);pdf.setFontSize(9);pdf.setTextColor(120,110,104);pdf.text(`${state.wedding.date||''} · Hostia: ${state.guests.length}`,margin,18);pdf.addImage(canvas.toDataURL('image/jpeg',.92),'JPEG',x,top,w,h,undefined,'FAST');pdf.save(`svadobny-plan-${state.wedding.date||new Date().toISOString().slice(0,10)}.pdf`);toast('PDF bolo vytvorené')}catch(error){console.error(error);toast('PDF sa nepodarilo vytvoriť')}finally{els.world.style.transform=oldTransform;selectedItem=oldSelected;renderItems();button.disabled=false;button.textContent=oldText}}
$('#pdfBtn').onclick=exportPdf;
$('#submitPlan').onclick=()=>{const cap=state.items.filter(isTable).reduce((a,t)=>a+t.seats,0),seated=state.guests.filter(g=>g.tableId).length,lines=[['Hostia',state.guests.length],['Stoly',state.items.filter(isTable).length],['Voľné miesta',cap-seated],['Hostia bez miesta',state.guests.length-seated],['Hostia s alergiou',state.guests.filter(g=>g.allergies.length).length],['Poznámka',state.wedding.note||'—'],['Posledné uloženie',new Date(state.meta.updatedAt).toLocaleString('sk-SK')]];const c=$('#summaryContent');c.replaceChildren(...lines.map(([a,b])=>{const p=document.createElement('p'),x=document.createElement('b');x.textContent=a+': ';p.append(x,document.createTextNode(b));return p}));showDialog($('#summaryDialog'))};$('#confirmSubmit').onclick=()=>{state.meta.submittedAt=new Date().toISOString();save();const stamp=state.meta.submittedAt.replace(/:/g,'-');download(JSON.stringify(state,null,2),`submissions/svadobny-plan-${stamp}.json`);closeDialog($('#summaryDialog'));toast('Finálna verzia bola uložená')};
window.addEventListener('beforeunload',save);renderLibrary();renderAll();
