const qs=new URLSearchParams(location.search);
const editToken=qs.get('token')||'';
const shareToken=qs.get('share')||'';
const accessToken=editToken||shareToken;
if(accessToken)document.querySelector('.logo-podorysu')?.setAttribute('href',location.href);
let readOnly=!!shareToken;
let projectLocked=false;
let loadedProject=null;
let lastSavedState='';
let saving=false;
let saveQueued=false;
let savePromise=null;
let eventStorageKey='event-planner-v1';

const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const status=document.createElement('div');status.id='serverSaveStatus';status.dataset.state=accessToken?'loading':'local';status.innerHTML=`<span class="status-dot"></span><span class="status-text">${accessToken?'Načítavam projekt…':'Lokálny režim'}</span>`;document.body.append(status);
let statusHideTimer;const setStatus=(text,state='saved')=>{clearTimeout(statusHideTimer);status.classList.remove('is-hidden');status.dataset.state=state;status.querySelector('.status-text').textContent=text;if(state==='saved')statusHideTimer=setTimeout(()=>status.classList.add('is-hidden'),2000)};
async function api(action,body){const response=await fetch(`api/project.php?action=${encodeURIComponent(action)}&token=${encodeURIComponent(accessToken)}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify({token:accessToken,action,...body}):undefined,cache:'no-store'});let data;try{data=await response.json()}catch{throw new Error('Server vrátil neplatnú odpoveď.')}if(!response.ok)throw new Error(data.error||'Chyba servera');return data;}
function showReviewBanner(){const review=loadedProject?.review;if(!review&&!projectLocked)return;const banner=document.createElement('div');banner.id='projectReviewBanner';const approved=loadedProject?.status==='approved';banner.className=approved?'approved':'revision';const content=document.createElement('div'),title=document.createElement('strong');title.textContent=approved?'Návrh bol schválený':'Návrh bol vrátený na dopracovanie';content.append(title);if(review?.note){const note=document.createElement('p');note.textContent=review.note;content.append(note)}const close=document.createElement('button');close.type='button';close.className='review-banner-close';close.setAttribute('aria-label','Zavrieť upozornenie');close.textContent='×';close.addEventListener('click',()=>banner.remove());banner.append(content,close);document.body.append(banner);}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const area=document.createElement('textarea');area.value=text;area.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();return copied;}}
function showShareDialog(){let dialog=document.getElementById('serverShareDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='serverShareDialog';dialog.innerHTML=`<form method="dialog" class="server-dialog-card"><div class="server-dialog-head"><div><small>Zdieľanie</small><h2>Zdieľaný náhľad</h2></div><button value="cancel" class="dialog-close" aria-label="Zavrieť">×</button></div><p>Osoba s týmto odkazom uvidí rozloženie sály a hostí, ale nebude môcť nič upravovať ani vymazať.</p><label class="server-check"><input id="shareShowDiet" type="checkbox"> Zobraziť alergie a stravovacie údaje</label><div class="server-dialog-actions"><button value="cancel" class="secondary">Zrušiť</button><button id="createShareLink" value="default" type="button">Vytvoriť a skopírovať odkaz</button></div></form>`;document.body.append(dialog);dialog.querySelector('#createShareLink').addEventListener('click',async()=>{const button=dialog.querySelector('#createShareLink');button.disabled=true;button.textContent='Vytváram…';try{const result=await api('share',{showDiet:dialog.querySelector('#shareShowDiet').checked});const url=new URL(location.href);url.search='';url.searchParams.set('share',result.shareToken);const copied=await copyText(url.href);button.textContent=copied?'Odkaz skopírovaný':'Odkaz vytvorený';setTimeout(()=>dialog.close(),900)}catch(error){button.textContent=error.message;setTimeout(()=>{button.textContent='Vytvoriť a skopírovať odkaz';button.disabled=false},1800)}})}dialog.showModal();}
function setupEventActions(){const shareButton=document.getElementById('zdielatNahlad'),submitButton=document.getElementById('odoslatPlan');if(shareButton){if(editToken&&!projectLocked)shareButton.onclick=showShareDialog;else shareButton.closest('.akcie-projektu')?.remove()}if(submitButton&&editToken&&!projectLocked)submitButton.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();showSubmitDialog()},true)}
function showSubmitDialog(){let dialog=document.getElementById('serverSubmitDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='serverSubmitDialog';dialog.innerHTML=`<form method="dialog" class="server-dialog-card"><div class="server-dialog-head"><div><small>Finálna verzia</small><h2>Odoslať organizátorom?</h2></div><button value="cancel" class="dialog-close" aria-label="Zavrieť">×</button></div><p>Aktuálny návrh sa uloží ako PDF verzia a organizátor ho skontroluje.</p><div class="server-dialog-actions"><button value="cancel" class="secondary">Ešte nie</button><button id="confirmServerSubmit" value="default" type="button">Odoslať návrh</button></div></form>`;document.body.append(dialog);dialog.querySelector('#confirmServerSubmit').addEventListener('click',async()=>{const button=dialog.querySelector('#confirmServerSubmit');button.disabled=true;button.textContent='Vytváram PDF…';try{await flushSave();const state=JSON.parse(localStorage.getItem(eventStorageKey)||'{}'),pdfBase64=await window.generatePlannerPdf();button.textContent='Odosielam…';await api('submit',{state,pdfBase64});lastSavedState=JSON.stringify(state);setStatus('Odoslané na kontrolu','submitted');button.textContent='Návrh bol odoslaný';document.getElementById('projectReviewBanner')?.remove();setTimeout(()=>dialog.close(),1000)}catch(error){button.textContent=error.message;setStatus('Odoslanie zlyhalo','error');setTimeout(()=>{button.textContent='Odoslať návrh';button.disabled=false},2000)}})}dialog.showModal();}
async function flushSave(){if(!editToken||projectLocked)return;if(saving){saveQueued=true;return savePromise;}const current=localStorage.getItem(eventStorageKey)||'';if(!current||current===lastSavedState)return;saving=true;setStatus('Ukladám…','saving');savePromise=(async()=>{try{await api('save',{state:JSON.parse(current)});lastSavedState=current;setStatus('Uložené','saved')}catch(error){setStatus(error.message,'error');throw error}finally{saving=false;savePromise=null}})();await savePromise;if(saveQueued){saveQueued=false;return flushSave()}}
function showPermissionRequired(){document.title='Vyžaduje sa povolenie';document.documentElement.classList.add('access-denied');document.body.innerHTML='<main class="access-denied-page"><section><img src="assets/bukovina.png" alt="Bukovina"><h1>Vyžaduje sa povolenie</h1><p>Editor je dostupný iba cez platný odkaz.<br>Požiadajte Bukovinu o prístup k vášmu eventu.</p></section></main>'}
let accessGranted=false;
if(accessToken){try{const data=await api('load');loadedProject=data.project;projectLocked=!!data.project.locked;if(projectLocked)readOnly=true;eventStorageKey=`event-planner-v1:${data.project.id}`;window.__EVENT_STORAGE_KEY__=eventStorageKey;localStorage.setItem(eventStorageKey,JSON.stringify(data.project.state));lastSavedState=JSON.stringify(data.project.state);document.title=`${data.project.name} – Svadobný plánovač`;setStatus(projectLocked?'Schválené – uzamknuté':(readOnly?'Iba náhľad':'Uložené'),projectLocked?'approved':(readOnly?'readonly':'saved'));accessGranted=true}catch(error){showPermissionRequired()}}else showPermissionRequired();
if(accessGranted){
 if(readOnly){document.documentElement.classList.add('readonly-mode');window.addEventListener('pointerdown',event=>{if(event.target.closest('.prvok-podorysu,.miesto'))event.stopImmediatePropagation()},true);window.addEventListener('dblclick',event=>{if(event.target.closest('.prvok-podorysu,.miesto')){event.preventDefault();event.stopImmediatePropagation()}},true);window.addEventListener('keydown',event=>{if(['Delete','Backspace'].includes(event.key)&&!event.target.matches('input,textarea'))event.preventDefault()},true);}
 const assetVersion=window.__ASSET_VERSION__||String(Math.floor(10000+Math.random()*90000));
 await import(`./app.js?v=${assetVersion}`);
 if(qs.get('export')==='pdf'&&editToken)setTimeout(()=>document.getElementById('vytvoritPdf')?.click(),400);
 showReviewBanner();setupEventActions();
 if(editToken&&!projectLocked){setInterval(()=>{const current=localStorage.getItem(eventStorageKey)||'';if(!current||current===lastSavedState)return;if(saving){saveQueued=true;return}flushSave().catch(()=>{})},1400);window.addEventListener('beforeunload',event=>{const current=localStorage.getItem(eventStorageKey)||'';if(current&&current!==lastSavedState){event.preventDefault();event.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushSave().catch(()=>{})});document.getElementById('serverShareButton')?.remove();}
}
