const qs=new URLSearchParams(location.search), editToken=qs.get('token')||'', shareToken=qs.get('share')||'', accessToken=editToken||shareToken, readOnly=!!shareToken;
const status=document.createElement('div');status.id='serverSaveStatus';status.textContent=accessToken?'Načítavam projekt…':'Lokálny režim';document.body.append(status);
async function api(action,body){const r=await fetch(`api/project.php?action=${encodeURIComponent(action)}&token=${encodeURIComponent(accessToken)}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify({token:accessToken,action,...body}):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Chyba servera');return data}
if(accessToken){try{const data=await api('load');localStorage.setItem('wedding-planner-v1',JSON.stringify(data.project.state));document.title=`${data.project.name} – Svadobný plánovač`;status.textContent=readOnly?'Zdieľaný náhľad':'Projekt načítaný';}catch(e){status.textContent=e.message;status.classList.add('error');}}
if(readOnly){document.documentElement.classList.add('readonly-mode');window.addEventListener('pointerdown',e=>{if(e.target.closest('.prvok-podorysu'))e.stopImmediatePropagation()},true);window.addEventListener('dblclick',e=>{if(e.target.closest('.prvok-podorysu'))e.preventDefault()},true);}
await import('./app.js?v=20260721-7');
if(editToken){let last=localStorage.getItem('wedding-planner-v1')||'',saving=false;setInterval(async()=>{const now=localStorage.getItem('wedding-planner-v1')||'';if(saving||!now||now===last)return;saving=true;status.textContent='Ukladám…';try{await api('save',{state:JSON.parse(now)});last=now;status.textContent='Uložené';status.classList.remove('error')}catch(e){status.textContent='Chyba ukladania';status.classList.add('error')}finally{saving=false}},1800);
const submit=document.getElementById('potvrditOdoslanie');submit?.addEventListener('click',async()=>{try{await api('submit',{state:JSON.parse(localStorage.getItem('wedding-planner-v1'))});status.textContent='Odoslané organizátorom'}catch(e){status.textContent=e.message}},true);
const share=document.createElement('button');share.id='serverShareButton';share.textContent='Zdieľať náhľad';share.onclick=async()=>{try{const x=await api('share',{showDiet:false});const url=new URL(location.href);url.search='';url.searchParams.set('share',x.shareToken);await navigator.clipboard.writeText(url.href);alert('Zdieľaný odkaz bol skopírovaný.')}catch(e){alert(e.message)}};document.querySelector('.akcie-projektu')?.append(share)}
