<?php
declare(strict_types=1);
require_once __DIR__.'/../config.php';
require_once __DIR__.'/email_templates.php';
function mail_configured():bool{return SMTP_HOST!==''&&SMTP_USER!==''&&SMTP_PASSWORD!==''&&MAIL_FROM!=='';}
function smtp_read($s):string{$r='';while(($l=fgets($s,1024))!==false){$r.=$l;if(strlen($l)<4||$l[3]===' ')break;}if($r===''){$meta=stream_get_meta_data($s);if(!empty($meta['timed_out']))throw new RuntimeException('SMTP server neodpovedal v časovom limite. Skontrolujte host, port a typ šifrovania.');if(!empty($meta['eof']))throw new RuntimeException('SMTP server ukončil spojenie bez odpovede. Skontrolujte kombináciu portu a šifrovania.');throw new RuntimeException('SMTP server neposlal žiadnu odpoveď.');}return $r;}
function smtp_expect($s,array $c,string $stage='komunikácia'):string{$r=smtp_read($s);$n=(int)substr($r,0,3);if(!in_array($n,$c,true))throw new RuntimeException('SMTP chyba počas kroku '.$stage.': '.trim($r));return $r;}
function smtp_command($s,string $cmd,array $c,string $stage='príkaz'):string{if(fwrite($s,$cmd."\r\n")===false)throw new RuntimeException('SMTP príkaz sa nepodarilo odoslať počas kroku '.$stage.'.');return smtp_expect($s,$c,$stage);}
function send_app_mail(string $to,string $subject,string $html,string $text=''):array{if(!filter_var($to,FILTER_VALIDATE_EMAIL))return['ok'=>false,'error'=>'Neplatná e-mailová adresa.'];if(!mail_configured())return['ok'=>false,'error'=>'SMTP nie je nastavené.'];$transport=SMTP_ENCRYPTION==='ssl'?'ssl://':'';$s=@stream_socket_client($transport.SMTP_HOST.':'.SMTP_PORT,$errno,$errstr,15,STREAM_CLIENT_CONNECT);if(!$s)return['ok'=>false,'error'=>'SMTP spojenie zlyhalo: '.$errstr];stream_set_timeout($s,15);try{smtp_expect($s,[220]);smtp_command($s,'EHLO '.($_SERVER['SERVER_NAME']??'localhost'),[250]);if(SMTP_ENCRYPTION==='tls'){smtp_command($s,'STARTTLS',[220]);if(!stream_socket_enable_crypto($s,true,STREAM_CRYPTO_METHOD_TLS_CLIENT))throw new RuntimeException('TLS spojenie sa nepodarilo aktivovať.');smtp_command($s,'EHLO '.($_SERVER['SERVER_NAME']??'localhost'),[250]);}smtp_command($s,'AUTH LOGIN',[334]);smtp_command($s,base64_encode(SMTP_USER),[334]);smtp_command($s,base64_encode(SMTP_PASSWORD),[235]);smtp_command($s,'MAIL FROM:<'.MAIL_FROM.'>',[250]);smtp_command($s,'RCPT TO:<'.$to.'>',[250,251]);smtp_command($s,'DATA',[354]);$b='b'.bin2hex(random_bytes(12));$plain=$text!==''?$text:trim(strip_tags(str_replace(['<br>','<br/>','<br />'],"\n",$html)));$headers=['From: '.MAIL_FROM_NAME.' <'.MAIL_FROM.'>','To: <'.$to.'>','Subject: =?UTF-8?B?'.base64_encode($subject).'?=','MIME-Version: 1.0','Content-Type: multipart/alternative; boundary="'.$b.'"','Date: '.date(DATE_RFC2822),'Message-ID: <'.bin2hex(random_bytes(12)).'@'.($_SERVER['SERVER_NAME']??'localhost').'>'];$body=implode("\r\n",$headers)."\r\n\r\n".'--'.$b."\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n".$plain."\r\n".'--'.$b."\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n".$html."\r\n".'--'.$b."--\r\n.";fwrite($s,str_replace("\r\n.","\r\n..",$body)."\r\n");smtp_expect($s,[250]);smtp_command($s,'QUIT',[221]);fclose($s);return['ok'=>true];}catch(Throwable $e){fclose($s);return['ok'=>false,'error'=>$e->getMessage()];}}
function email_layout(string $title,string $content,string $buttonLabel='',string $buttonUrl=''):string{$button=$buttonUrl!==''&&$buttonLabel!==''?'<p style="margin:28px 0"><a href="'.htmlspecialchars($buttonUrl,ENT_QUOTES).'" style="display:inline-block;background:#708e8e;color:#fff;text-decoration:none;padding:13px 20px;border-radius:10px;font-weight:700">'.htmlspecialchars($buttonLabel).'</a></p>':'';return '<!doctype html><html><body style="margin:0;background:#f4f7f7;font-family:Arial,sans-serif;color:#243535"><div style="max-width:620px;margin:30px auto;background:#fff;border-radius:16px;padding:32px"><h1 style="font-size:25px">'.htmlspecialchars($title).'</h1>'.$content.$button.'<p style="margin-top:32px;color:#748383;font-size:13px">'.htmlspecialchars(MAIL_FROM_NAME).'</p></div></body></html>';}
function send_from_template(string $key,string $to,array $project,string $buttonUrl='',array $extra=[]):array{$t=get_rendered_email_template($key,$project,$extra);return send_app_mail($to,$t['subject'],email_layout($t['title'],$t['body'],$t['buttonLabel'],$buttonUrl));}
function send_client_invitation(array $p,string $url):array{return send_from_template('invitation',(string)($p['client']['email']??''),$p,$url);}
function send_submission_notifications(array $p,string $adminUrl=''):array{$r=[];if(ORGANIZER_EMAIL!=='')$r['organizer']=send_from_template('submission_organizer',ORGANIZER_EMAIL,$p,$adminUrl);$email=(string)($p['client']['email']??'');if($email!=='')$r['client']=send_from_template('submission_client',$email,$p);return$r;}
function send_review_decision(array $p,string $decision,string $note,string $editUrl):array{$email=(string)($p['client']['email']??'');if($email==='')return['ok'=>false,'error'=>'Klient nemá e-mail.'];$key=$decision==='approved'?'approved':'revision';return send_from_template($key,$email,$p,$decision==='approved'?'':$editUrl,['review_note'=>$note]);}
