<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
function ensure_storage(): void { foreach ([DATA_DIR, PROJECT_DIR, VERSION_DIR] as $d) if (!is_dir($d)) mkdir($d, 0775, true); }
function json_response(array $data, int $status=200): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store'); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function enable_asset_versioning(): void { static $enabled=false;if($enabled)return;$enabled=true;$version=(string)random_int(10000,99999);ob_start(static function(string $html)use($version):string{$html=str_replace('<header><b>Bukovina Planner</b>','<header><a class="admin-logo" href="index.php" aria-label="Bukovina Planner"><img src="../assets/bukovina.png" alt="Bukovina Planner"></a>',$html);$html=str_replace('<h1>Bukovina Planner</h1>','<h1 class="admin-login-logo"><img src="../assets/bukovina.png" alt="Bukovina Planner"></h1>',$html);$html=strtr($html,['Názov svadby'=>'Názov eventu','názov svadby'=>'názov eventu','Dátum svadby'=>'Dátum eventu','dátum svadby'=>'dátum eventu','Svadba Novákovci'=>'Event Novákovci','Svadobné'=>'Eventové','Svadobná'=>'Eventová','Svadobný'=>'Eventový','svadobné'=>'eventové','svadobná'=>'eventová','svadobný'=>'eventový','projektov'=>'eventov','Projektov'=>'Eventov','projektu'=>'eventu','Projektu'=>'Eventu','projektom'=>'eventom','Projektom'=>'Eventom','projekty'=>'eventy','Projekty'=>'Eventy','projekt'=>'event','Projekt'=>'Event']);$html=str_replace('</head>','<link rel="stylesheet" href="layout.css"></head>',$html);return(string)preg_replace('/((?:href|src)="(?!https?:\/\/)[^"?]+\.(?:css|js))(?:\?v=[^"]*)?"/','$1?v='.$version.'"',$html);}); }
function read_json(string $file, array $fallback=[]): array { if (!is_file($file)) return $fallback; $v=json_decode((string)file_get_contents($file), true); return is_array($v)?$v:$fallback; }
function write_json(string $file, array $data): void { ensure_storage(); if(str_starts_with(str_replace('\\','/',$file),rtrim(str_replace('\\','/',PROJECT_DIR),'/').'/')&&isset($data['access']['shareToken']))$data['access']['shareEnabled']=true;$tmp=$file.'.tmp'; if(file_put_contents($tmp,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX)===false) throw new RuntimeException('Súbor sa nepodarilo zapísať.'); if(!rename($tmp,$file)) throw new RuntimeException('Súbor sa nepodarilo uložiť.'); }
function token(int $bytes=24): string { return bin2hex(random_bytes($bytes)); }
function project_path(string $id): string { return PROJECT_DIR.'/'.preg_replace('/[^a-zA-Z0-9_-]/','',$id).'.json'; }
function all_projects(): array { ensure_storage(); $out=[]; foreach (glob(PROJECT_DIR.'/*.json') ?: [] as $f) { $p=read_json($f); if ($p) $out[]=$p; } usort($out,fn($a,$b)=>strcmp($b['meta']['updatedAt']??'', $a['meta']['updatedAt']??'')); return $out; }
function find_project_by_token(string $value, string &$mode=''): ?array { foreach (all_projects() as $p) { if (hash_equals((string)($p['access']['editToken']??''),$value)) {$mode='edit';return $p;} if (hash_equals((string)($p['access']['shareToken']??''),$value)) {$mode='share';return $p;} } return null; }
function activity_add(array &$project,string $type,string $actor,string $label,array $details=[],int $dedupeSeconds=0): void { $now=time();$items=$project['activity']??[];$last=$items?end($items):null;if($dedupeSeconds>0&&is_array($last)&&($last['type']??'')===$type&&($last['actor']??'')===$actor&&$now-strtotime((string)($last['at']??'1970-01-01'))<$dedupeSeconds)return;$items[]=['id'=>token(6),'type'=>$type,'actor'=>$actor,'label'=>$label,'details'=>$details,'at'=>gmdate('c')];$project['activity']=array_slice($items,-250); }
function secure_session_start(): void { if(session_status()===PHP_SESSION_NONE){session_set_cookie_params(['httponly'=>true,'secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'samesite'=>'Lax']);session_start();} }
function admin_required(): void { secure_session_start(); if (empty($_SESSION['admin'])) { header('Location: index.php'); exit; } }
function csrf_token(): string { secure_session_start(); return $_SESSION['csrf'] ??= token(24); }
function csrf_field(): string { return '<input type="hidden" name="csrf" value="'.htmlspecialchars(csrf_token(),ENT_QUOTES,'UTF-8').'">'; }
function verify_csrf(): void { secure_session_start(); if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??''))){http_response_code(419);exit('Platnosť formulára vypršala. Obnovte stránku a skúste to znova.');} }
function security_status(): array { ensure_storage(); return ['dataExists'=>is_dir(DATA_DIR),'dataWritable'=>is_writable(DATA_DIR),'projectsWritable'=>is_writable(PROJECT_DIR),'versionsWritable'=>is_writable(VERSION_DIR),'phpVersion'=>PHP_VERSION,'https'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')]; }
