<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';
require_once __DIR__.'/../lib/mailer.php';
enable_asset_versioning();
ensure_storage();
secure_session_start();
$users=normalize_admin_users(read_json(USER_FILE));
if(!$users){header('Location:../install/');exit;}
restore_admin_from_cookie($users);
if(isset($_GET['logout'])){revoke_current_admin_token($users);$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();header('Location:index.php');exit;}
$error='';$message='';$lockedUntil=(int)($_SESSION['login_locked_until']??0);
function admin_root_url():string{if(BASE_URL!=='')return BASE_URL;$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$script=str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/admin/index.php'));$root=rtrim(dirname($script),'/');return $scheme.'://'.$host.($root==='/'?'':$root);}
if(isset($_POST['login'])){
 verify_csrf();
 if(time()<$lockedUntil){$error='Príliš veľa pokusov. Skúste to neskôr.';}
 else{
  $email=trim((string)($_POST['email']??''));$password=(string)($_POST['password']??'');$index=null;
  foreach($users as $i=>$candidate)if(strcasecmp((string)($candidate['email']??''),$email)===0){$index=$i;break;}
  $validCurrent=$index!==null&&password_verify($password,(string)($users[$index]['passwordHash']??''));
  $validReset=$index!==null&&!empty($users[$index]['resetPasswordHash'])&&password_verify($password,(string)$users[$index]['resetPasswordHash']);
  if($index!==null&&($validCurrent||$validReset)){
   if($validReset){$users[$index]['passwordHash']=$users[$index]['resetPasswordHash'];$users[$index]['passwordChangedAt']=gmdate('c');unset($users[$index]['resetPasswordHash'],$users[$index]['resetPasswordCreatedAt']);}
   session_regenerate_id(true);$_SESSION['admin']=$users[$index]['email'];unset($_SESSION['login_attempts'],$_SESSION['login_locked_until']);issue_admin_remember_token($users,$index);header('Location:'.(!empty($users[$index]['mustChangePassword'])?'settings.php?password=required':'index.php'));exit;
  }
  $_SESSION['login_attempts']=(int)($_SESSION['login_attempts']??0)+1;if($_SESSION['login_attempts']>=5){$_SESSION['login_locked_until']=time()+600;$_SESSION['login_attempts']=0;}$error='Nesprávny e-mail alebo heslo.';
 }
}
if(isset($_POST['resetPassword'])){
 verify_csrf();$email=trim((string)($_POST['resetEmail']??''));$last=(int)($_SESSION['password_reset_at']??0);
 if(time()-$last<300){$error='Nové heslo už bolo nedávno vyžiadané. Skúste to o niekoľko minút.';}
 elseif(!mail_configured()){$error='Obnovenie hesla nie je dostupné, pretože SMTP nie je nastavené.';}
 else{
  $_SESSION['password_reset_at']=time();$index=null;foreach($users as $i=>$candidate)if(strcasecmp((string)($candidate['email']??''),$email)===0){$index=$i;break;}
  if($index!==null){$newPassword=generated_admin_password();$result=send_admin_password_reset((string)$users[$index]['email'],$newPassword);if($result['ok']){$users[$index]['resetPasswordHash']=password_hash($newPassword,PASSWORD_DEFAULT);$users[$index]['resetPasswordCreatedAt']=gmdate('c');write_json(USER_FILE,$users);}else{$error='E-mail sa nepodarilo odoslať: '.($result['error']??'Neznáma chyba.');}}
  if($error==='')$message='Ak účet s týmto e-mailom existuje, nové heslo bolo odoslané.';
 }
}
if(empty($_SESSION['admin'])){?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="style.css"><title>Prihlásenie</title></head><body class="login"><div class="login-stack"><form method="post" class="login-card"><?=csrf_field()?><h1>Bukovina Planner</h1><?php if($message):?><div class="notice"><?=htmlspecialchars($message)?></div><?php endif?><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?><label>E-mail<input type="email" name="email" required autocomplete="username"></label><label>Heslo<input type="password" name="password" required autocomplete="current-password"></label><button name="login">Prihlásiť sa</button></form><details class="password-recovery"><summary>Obnoviť heslo</summary><form method="post" class="recovery-form"><?=csrf_field()?><p>Zadajte e-mail administrátorského účtu. Nové vygenerované heslo vám príde e-mailom.</p><label>E-mail<input type="email" name="resetEmail" required autocomplete="email"></label><button name="resetPassword">Odoslať nové heslo</button></form></details></div></body></html><?php exit;}
if(isset($_POST['create'])){verify_csrf();$email=trim((string)($_POST['email']??''));$name=trim((string)($_POST['name']??''));$clientName='';$weddingDate=trim((string)($_POST['weddingDate']??''));$sendNow=!empty($_POST['sendNow']);if(!filter_var($email,FILTER_VALIDATE_EMAIL)){$error='Zadajte platný e-mail klienta.';}elseif($name===''||$weddingDate===''){$error='Vyplňte názov eventu a dátum.';}else{$id='event-'.date('Ymd').'-'.substr(token(5),0,8);$edit=token();$now=gmdate('c');$project=['id'=>$id,'name'=>$name,'client'=>['name'=>$clientName,'email'=>$email],'weddingDate'=>$weddingDate,'status'=>'not-opened','access'=>['editToken'=>$edit,'shareToken'=>token(),'shareEnabled'=>false],'share'=>['showDiet'=>false],'state'=>['schemaVersion'=>1,'projectId'=>$id,'wedding'=>['eventName'=>$name,'date'=>$weddingDate,'contactName'=>$clientName,'phone'=>'','email'=>$email,'note'=>''],'settings'=>['zoom'=>0.72,'panX'=>60,'panY'=>35],'items'=>default_event_items(),'guests'=>[],'meta'=>['createdAt'=>$now,'updatedAt'=>$now,'submittedAt'=>null]],'meta'=>['createdAt'=>$now,'updatedAt'=>$now,'submittedAt'=>null]];activity_add($project,'project-created','admin','Projekt bol vytvorený');write_json(project_path($id),$project);$redirect='project.php?id='.rawurlencode($id).'&created=1';if($sendNow){if(mail_configured()){$editUrl=admin_root_url().'/?token='.rawurlencode($edit);$result=send_client_invitation($project,$editUrl);if($result['ok']){$project['meta']['invitationSentAt']=gmdate('c');$project['meta']['invitationSentTo']=$email;activity_add($project,'invitation-sent','admin','Pozvánka bola odoslaná klientovi');write_json(project_path($id),$project);$redirect.='&mail=sent';}else{$redirect.='&mail=error&message='.rawurlencode((string)($result['error']??'E-mail sa nepodarilo odoslať.'));}}else{$redirect.='&mail=error&message='.rawurlencode('Projekt bol vytvorený, ale SMTP nie je nastavené. Odkaz môžete skopírovať v detaile projektu.');}}header('Location:'.$redirect);exit;}}
function event_count_label(int $count):string{$lastTwo=$count%100;$last=$count%10;$word=($last===1&&$lastTwo!==11)?'event':(($last>=2&&$last<=4&&($lastTwo<12||$lastTwo>14))?'eventy':'eventov');return $count.' '.$word;}
$all=all_projects();$statusLabels=['not-opened'=>'Neotvorený','editing'=>'Rozpracovaný','sent'=>'Na kontrolu','revision-requested'=>'Na dopracovanie','approved'=>'Schválený','changed-after-send'=>'Zmenený po odoslaní','archived'=>'Archivovaný'];$counts=array_fill_keys(array_keys($statusLabels),0);foreach($all as $p)$counts[$p['status']??'editing']=($counts[$p['status']??'editing']??0)+1;$q=trim((string)($_GET['q']??''));$filter=(string)($_GET['status']??'active');$projects=array_values(array_filter($all,function($p)use($q,$filter){$status=$p['status']??'editing';if($filter==='active'&&$status==='archived')return false;if($filter!=='all'&&$filter!=='active'&&$status!==$filter)return false;if($q==='')return true;$hay=mb_strtolower(($p['name']??'').' '.($p['client']['name']??'').' '.($p['client']['email']??'').' '.($p['weddingDate']??''));return str_contains($hay,mb_strtolower($q));}));
?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="../css/fontawesome.css"><link rel="stylesheet" href="../css/sharp-light.css"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="icons.css"><title>Administrácia</title></head><body><header><b>Bukovina Planner</b><nav><a href="index.php">Projekty</a><a href="settings.php" class="header-icon" title="Nastavenia" aria-label="Nastavenia"><i class="fa-sharp fa-light fa-gear" aria-hidden="true"></i></a><a href="?logout=1" class="header-icon" title="Odhlásiť sa" aria-label="Odhlásiť sa"><i class="fa-sharp fa-light fa-circle-xmark" aria-hidden="true"></i></a></nav></header><main><section class="hero"><div><h1>Eventy</h1><p><?=event_count_label(count($all))?></p></div><button onclick="document.getElementById('newProject').showModal()">+ Nový projekt</button></section><?php if(isset($_GET['deleted'])):?><div class="notice">Projekt a všetky jeho odoslané verzie boli odstránené.</div><?php endif?><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?>
<section class="dashboard-stats"><a href="?status=not-opened"><b><?=$counts['not-opened']?></b><span>Neotvorené</span></a><a href="?status=editing"><b><?=$counts['editing']?></b><span>Rozpracované</span></a><a class="event-alert-card<?=$counts['sent']>0?' has-events':''?>" href="?status=sent"><b><?=$counts['sent']?></b><span>Na kontrolu</span></a><a class="event-alert-card<?=$counts['revision-requested']>1?' has-events':''?>" href="?status=revision-requested"><b><?=$counts['revision-requested']?></b><span>Na dopracovanie</span></a><a href="?status=approved"><b><?=$counts['approved']?></b><span>Schválené</span></a><a class="event-alert-card<?=$counts['changed-after-send']>1?' has-events':''?>" href="?status=changed-after-send"><b><?=$counts['changed-after-send']?></b><span>Po odoslaní zmenené</span></a></section>
<form method="get" class="project-filters"><label class="search-field">Hľadať<input type="search" name="q" value="<?=htmlspecialchars($q)?>" placeholder="Názov, klient alebo e-mail"></label><label>Stav<select name="status"><option value="active" <?=$filter==='active'?'selected':''?>>Aktívne projekty</option><option value="all" <?=$filter==='all'?'selected':''?>>Všetky projekty</option><?php foreach($statusLabels as $key=>$label):?><option value="<?=htmlspecialchars($key)?>" <?=$filter===$key?'selected':''?>><?=htmlspecialchars($label)?></option><?php endforeach?></select></label><button>Filtrovať</button><?php if($q!==''||$filter!=='active'):?><a href="index.php" class="button-link secondary-link">Zrušiť filter</a><?php endif?></form>
<div class="projects"><?php if(!$projects):?><div class="empty-state"><h2>Nenašli sa žiadne projekty</h2><p>Zmeňte vyhľadávanie alebo filter.</p></div><?php endif?><?php foreach($projects as $p):$detail='project.php?id='.urlencode($p['id']);?><article><div><h2><a class="project-title" href="<?=htmlspecialchars($detail)?>"><?=htmlspecialchars($p['name']?:'Nový event')?></a></h2><p><?=htmlspecialchars($p['client']['email']??'')?><?php if(!empty($p['weddingDate'])):?> · <?=htmlspecialchars(format_date_sk($p['weddingDate']))?><?php endif?></p><small><?=!empty($p['meta']['lastOpenedAt'])?'Klient naposledy otvoril '.htmlspecialchars(format_date_sk($p['meta']['lastOpenedAt'])):'Klient zatiaľ neotvoril odkaz'?></small></div><span class="status"><?=htmlspecialchars($statusLabels[$p['status']]??$p['status'])?></span><a class="project-editor-link" href="../?token=<?=urlencode($p['access']['editToken'])?>" target="_blank">Editor</a><a class="button-link project-detail-link" href="<?=htmlspecialchars($detail)?>">Detail</a></article><?php endforeach?></div></main><dialog id="newProject"><form method="post"><?=csrf_field()?><h2>Nový event</h2><label>Názov eventu<input name="name" required placeholder="Event Novákovci"></label><label>E-mail klienta<input type="email" name="email" required placeholder="jan@example.sk"></label><label>Dátum eventu<input type="date" name="weddingDate" required></label><label class="check-row"><input type="checkbox" name="sendNow" value="1" checked> Po vytvorení odoslať klientovi editačný odkaz</label><?php if(!mail_configured()):?><small class="warning">SMTP nie je nastavené. Projekt sa vytvorí, ale e-mail sa neodošle.</small><?php else:?><small>Klient dostane súkromný odkaz, cez ktorý môže návrh upravovať a vytvoriť share odkaz iba na prezeranie.</small><?php endif?><div class="new-project-actions"><button type="button" onclick="this.closest('dialog').close()">Zrušiť</button><button name="create">Vytvoriť event</button></div></form></dialog></body></html>
