<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';
ensure_storage();
session_start();
if(isset($_GET['logout'])){session_destroy();header('Location:index.php');exit;}
$users=read_json(USER_FILE);if(!$users){$users=[['email'=>'admin@example.sk','passwordHash'=>password_hash('ZmenMa123!',PASSWORD_DEFAULT),'name'=>'Správca sály']];write_json(USER_FILE,$users);}
$error='';if(isset($_POST['login'])){$u=array_values(array_filter($users,fn($x)=>strcasecmp($x['email'],trim($_POST['email']??''))===0))[0]??null;if($u&&password_verify((string)($_POST['password']??''),$u['passwordHash'])){$_SESSION['admin']=$u['email'];header('Location:index.php');exit;}$error='Nesprávny e-mail alebo heslo.';}
if(empty($_SESSION['admin'])){?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="style.css"><title>Prihlásenie</title></head><body class="login"><form method="post" class="login-card"><h1>Bukovina Planner</h1><p>Administrácia svadobnej sály</p><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?><label>E-mail<input type="email" name="email" required></label><label>Heslo<input type="password" name="password" required></label><button name="login">Prihlásiť sa</button><small>Prvé prihlásenie: admin@example.sk / ZmenMa123!</small></form></body></html><?php exit;}
if(isset($_POST['create'])){$email=trim($_POST['email']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)){$error='Zadajte platný e-mail klienta.';}else{$id='event-'.date('Ymd').'-'.substr(token(5),0,8);$edit=token();$project=['id'=>$id,'name'=>'Nový event','client'=>['name'=>'','email'=>$email],'weddingDate'=>'','status'=>'not-opened','access'=>['editToken'=>$edit,'shareToken'=>token(),'shareEnabled'=>false],'share'=>['showDiet'=>false],'state'=>['schemaVersion'=>1,'projectId'=>$id,'wedding'=>['eventName'=>'','date'=>'','contactName'=>'','phone'=>'','email'=>$email,'note'=>''],'settings'=>['zoom'=>0.72,'panX'=>60,'panY'=>35],'items'=>[],'guests'=>[],'meta'=>['createdAt'=>gmdate('c'),'updatedAt'=>gmdate('c'),'submittedAt'=>null]],'meta'=>['createdAt'=>gmdate('c'),'updatedAt'=>gmdate('c'),'submittedAt'=>null]];write_json(project_path($id),$project);$_SESSION['created_link']='../?token='.$edit;header('Location:index.php');exit;}}
function event_count_label(int $count):string{$lastTwo=$count%100;$last=$count%10;$word=($last===1&&$lastTwo!==11)?'event':(($last>=2&&$last<=4&&($lastTwo<12||$lastTwo>14))?'eventy':'eventov');return $count.' '.$word;}
$projects=all_projects();$statusLabels=['not-opened'=>'Neotvorený','editing'=>'Rozpracovaný','sent'=>'Odoslaný','changed-after-send'=>'Zmenený po odoslaní'];?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="../css/fontawesome.css"><link rel="stylesheet" href="../css/sharp-light.css"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="icons.css"><title>Administrácia</title></head><body><header><b>Bukovina Planner</b><a href="?logout=1">Odhlásiť sa</a></header><main><section class="hero"><div><h1>Eventy</h1><p><?=event_count_label(count($projects))?></p></div><button onclick="document.getElementById('newProject').showModal()">+ Nový projekt</button></section><?php if(!empty($error)):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?><?php if($l=$_SESSION['created_link']??''):unset($_SESSION['created_link']);?><div class="notice">Projekt vytvorený. <a href="<?=htmlspecialchars($l)?>">Otvoriť editor</a> <button type="button" class="copy-link" data-copy-link="<?=htmlspecialchars($l)?>" title="Kopírovať odkaz" aria-label="Kopírovať odkaz"><i class="fa-sharp fa-light fa-duplicate" aria-hidden="true"></i></button></div><?php endif?><div class="projects"><?php foreach($projects as $p):$link='../?token='.urlencode($p['access']['editToken']);?><article><div><h2><?=htmlspecialchars($p['name']?:'Nový event')?></h2><p><?=htmlspecialchars($p['client']['email']??'')?><?php if(!empty($p['weddingDate'])):?> · <?=htmlspecialchars($p['weddingDate'])?><?php endif?></p></div><span class="status"><?=htmlspecialchars($statusLabels[$p['status']]??$p['status'])?></span><a href="<?=htmlspecialchars($link)?>">Otvoriť</a><button type="button" class="copy-link" data-copy-link="<?=htmlspecialchars($link)?>" title="Kopírovať odkaz" aria-label="Kopírovať odkaz"><i class="fa-sharp fa-light fa-duplicate" aria-hidden="true"></i></button></article><?php endforeach?></div></main><dialog id="newProject"><form method="post"><h2>Nový projekt</h2><label>E-mail klienta<input type="email" name="email" required></label><small>Názov eventu a ostatné údaje si klient doplní v editore.</small><div><button type="button" onclick="this.closest('dialog').close()">Zrušiť</button><button name="create">Vytvoriť projekt</button></div></form></dialog><script>
async function copyProjectLink(button){const url=new URL(button.dataset.copyLink,location.href).href;try{if(!navigator.clipboard)throw new Error();await navigator.clipboard.writeText(url)}catch(e){const input=document.createElement('textarea');input.value=url;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied){window.prompt('Skopírujte odkaz:',url);return}}button.classList.add('copied');button.title='Odkaz skopírovaný';button.setAttribute('aria-label','Odkaz skopírovaný');setTimeout(()=>{button.classList.remove('copied');button.title='Kopírovať odkaz';button.setAttribute('aria-label','Kopírovať odkaz')},1800)}
document.querySelectorAll('[data-copy-link]').forEach(button=>button.addEventListener('click',()=>copyProjectLink(button)));
</script></body></html>
