<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';ensure_storage();secure_session_start();
if(isset($_GET['logout'])){session_destroy();header('Location:index.php');exit;}
$users=read_json(USER_FILE);if(!$users){$users=[['email'=>'admin@example.sk','passwordHash'=>password_hash('ZmenMa123!',PASSWORD_DEFAULT),'name'=>'Správca sály']];write_json(USER_FILE,$users);}
$error='';$lockedUntil=(int)($_SESSION['login_locked_until']??0);
if(isset($_POST['login'])){verify_csrf();if(time()<$lockedUntil){$error='Príliš veľa pokusov. Skúste to neskôr.';}else{$u=array_values(array_filter($users,fn($x)=>strcasecmp($x['email'],trim($_POST['email']??''))===0))[0]??null;if($u&&password_verify((string)($_POST['password']??''),$u['passwordHash'])){session_regenerate_id(true);$_SESSION['admin']=$u['email'];unset($_SESSION['login_attempts'],$_SESSION['login_locked_until']);header('Location:index.php');exit;}$_SESSION['login_attempts']=(int)($_SESSION['login_attempts']??0)+1;if($_SESSION['login_attempts']>=5){$_SESSION['login_locked_until']=time()+600;$_SESSION['login_attempts']=0;}$error='Nesprávny e-mail alebo heslo.';}}
if(empty($_SESSION['admin'])){?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="style.css"><title>Prihlásenie</title></head><body class="login"><form method="post" class="login-card"><?=csrf_field()?><h1>Bukovina Planner</h1><p>Administrácia svadobnej sály</p><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?><label>E-mail<input type="email" name="email" required autocomplete="username"></label><label>Heslo<input type="password" name="password" required autocomplete="current-password"></label><button name="login">Prihlásiť sa</button><small>Po prvom prihlásení zmeňte predvolené heslo v Nastaveniach.</small></form></body></html><?php exit;}
if(isset($_POST['create'])){verify_csrf();$email=trim($_POST['email']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)){$error='Zadajte platný e-mail klienta.';}else{$id='event-'.date('Ymd').'-'.substr(token(5),0,8);$edit=token();$project=['id'=>$id,'name'=>'Nový event','client'=>['name'=>'','email'=>$email],'weddingDate'=>'','status'=>'not-opened','access'=>['editToken'=>$edit,'shareToken'=>token(),'shareEnabled'=>false],'share'=>['showDiet'=>false],'state'=>['schemaVersion'=>1,'projectId'=>$id,'wedding'=>['eventName'=>'','date'=>'','contactName'=>'','phone'=>'','email'=>$email,'note'=>''],'settings'=>['zoom'=>0.72,'panX'=>60,'panY'=>35],'items'=>[],'guests'=>[],'meta'=>['createdAt'=>gmdate('c'),'updatedAt'=>gmdate('c'),'submittedAt'=>null]],'meta'=>['createdAt'=>gmdate('c'),'updatedAt'=>gmdate('c'),'submittedAt'=>null]];write_json(project_path($id),$project);header('Location:project.php?id='.rawurlencode($id));exit;}}
function event_count_label(int $count):string{$lastTwo=$count%100;$last=$count%10;$word=($last===1&&$lastTwo!==11)?'event':(($last>=2&&$last<=4&&($lastTwo<12||$lastTwo>14))?'eventy':'eventov');return $count.' '.$word;}
$projects=all_projects();$statusLabels=['not-opened'=>'Neotvorený','editing'=>'Rozpracovaný','sent'=>'Odoslaný','changed-after-send'=>'Zmenený po odoslaní','archived'=>'Archivovaný'];?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="../css/fontawesome.css"><link rel="stylesheet" href="../css/sharp-light.css"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="icons.css"><title>Administrácia</title></head><body><header><b>Bukovina Planner</b><nav><a href="index.php">Projekty</a><a href="settings.php">Nastavenia</a><a href="?logout=1">Odhlásiť sa</a></nav></header><main><section class="hero"><div><h1>Eventy</h1><p><?=event_count_label(count($projects))?></p></div><button onclick="document.getElementById('newProject').showModal()">+ Nový projekt</button></section><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif?><div class="projects"><?php foreach($projects as $p):$detail='project.php?id='.urlencode($p['id']);?><article><div><h2><a class="project-title" href="<?=htmlspecialchars($detail)?>"><?=htmlspecialchars($p['name']?:'Nový event')?></a></h2><p><?=htmlspecialchars($p['client']['email']??'')?><?php if(!empty($p['weddingDate'])):?> · <?=htmlspecialchars($p['weddingDate'])?><?php endif?></p></div><span class="status"><?=htmlspecialchars($statusLabels[$p['status']]??$p['status'])?></span><a class="button-link" href="<?=htmlspecialchars($detail)?>">Detail</a><a href="../?token=<?=urlencode($p['access']['editToken'])?>" target="_blank">Editor</a></article><?php endforeach?></div></main><dialog id="newProject"><form method="post"><?=csrf_field()?><h2>Nový projekt</h2><label>E-mail klienta<input type="email" name="email" required></label><small>Názov eventu a ostatné údaje je možné doplniť v detaile projektu alebo v editore.</small><div><button type="button" onclick="this.closest('dialog').close()">Zrušiť</button><button name="create">Vytvoriť projekt</button></div></form></dialog></body></html>