<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';
admin_required();ensure_storage();enable_asset_versioning();
$users=read_json(USER_FILE);$current=$_SESSION['admin'];$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['changePassword'])){verify_csrf();$old=(string)($_POST['oldPassword']??'');$new=(string)($_POST['newPassword']??'');$confirm=(string)($_POST['confirmPassword']??'');$index=array_search(strtolower($current),array_map(fn($u)=>strtolower((string)$u['email']),$users),true);if($index===false||!password_verify($old,(string)$users[$index]['passwordHash']))$error='Aktuálne heslo nie je správne.';elseif(strlen($new)<12)$error='Nové heslo musí mať aspoň 12 znakov.';elseif($new!==$confirm)$error='Nové heslá sa nezhodujú.';else{$users[$index]['passwordHash']=password_hash($new,PASSWORD_DEFAULT);$users[$index]['passwordChangedAt']=gmdate('c');write_json(USER_FILE,$users);session_regenerate_id(true);$message='Heslo bolo zmenené.';}}
if(($_GET['restore']??'')==='ok')$message='Záloha bola obnovená. Importovaných projektov: '.(int)($_GET['projects']??0).'.';elseif(($_GET['restore']??'')==='upload-error')$error='Súbor zálohy sa nepodarilo nahrať.';elseif(($_GET['restore']??'')==='too-large')$error='Záloha je väčšia ako povolených 50 MB.';elseif(($_GET['restore']??'')==='error')$error=(string)($_GET['message']??'Zálohu sa nepodarilo obnoviť.');
$status=security_status();$backupCount=count(glob(DATA_DIR.'/backups/before-restore-*.json')?:[]);function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="sk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="../css/fontawesome.css"><link rel="stylesheet" href="../css/sharp-light.css"><link rel="stylesheet" href="style.css"><title>Nastavenia – Bukovina Planner</title></head><body><header><b>Bukovina Planner</b><nav><a class="header-icon" href="settings.php" title="Nastavenia" aria-label="Nastavenia"><i class="fa-sharp fa-light fa-gear" aria-hidden="true"></i></a><a class="header-icon" href="index.php?logout=1" title="Odhlásiť sa" aria-label="Odhlásiť sa"><i class="fa-sharp fa-light fa-circle-xmark" aria-hidden="true"></i></a></nav></header><main><a class="back" href="index.php">← Späť na projekty</a><section class="hero project-hero"><div><h1>Nastavenia a bezpečnosť</h1><p><?=h($current)?></p></div></section><?php if($message):?><div class="notice"><?=h($message)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="detail-grid"><section class="card"><h2>Zmeniť heslo</h2><form method="post" class="form-grid single-column"><?=csrf_field()?><input type="hidden" name="changePassword" value="1"><label>Aktuálne heslo<input type="password" name="oldPassword" required autocomplete="current-password"></label><label>Nové heslo<input type="password" name="newPassword" required minlength="12" autocomplete="new-password"></label><label>Zopakovať nové heslo<input type="password" name="confirmPassword" required minlength="12" autocomplete="new-password"></label><button>Zmeniť heslo</button></form></section><section class="card stats-card"><h2>Kontrola servera</h2><dl><div><dt>PHP</dt><dd><?=h($status['phpVersion'])?></dd></div><div><dt>HTTPS</dt><dd class="<?=$status['https']?'ok':'warning'?>"><?=$status['https']?'Aktívne':'Neaktívne'?></dd></div><div><dt>Priečinok data</dt><dd class="<?=$status['dataWritable']?'ok':'bad'?>"><?=$status['dataWritable']?'Zapisovateľný':'Bez zápisu'?></dd></div><div><dt>Projekty</dt><dd class="<?=$status['projectsWritable']?'ok':'bad'?>"><?=$status['projectsWritable']?'Zapisovateľné':'Bez zápisu'?></dd></div><div><dt>Verzie</dt><dd class="<?=$status['versionsWritable']?'ok':'bad'?>"><?=$status['versionsWritable']?'Zapisovateľné':'Bez zápisu'?></dd></div><div><dt>Interné poistné zálohy</dt><dd><?=$backupCount?></dd></div></dl></section></div>
<section class="card"><h2>E-mailové šablóny</h2><p class="muted">Upravte predmety a texty pozvánky, potvrdenia, schválenia aj vrátenia na dopracovanie. Zmeny sa použijú pri najbližšom odoslaní.</p><a class="button-link" href="email-templates.php">Spravovať e-mailové šablóny</a></section>
<section class="card backup-card"><h2>Záloha systému</h2><p class="muted">Záloha obsahuje všetky projekty, odoslané verzie, e-mailové šablóny a administrátorské účty. SMTP heslá v nej nie sú, pretože sa ukladajú v prostredí servera.</p><a class="button-link" href="backup.php?action=download">Stiahnuť kompletnú zálohu</a></section>
<section class="card restore-card"><h2>Obnoviť zo zálohy</h2><div class="warning-box">Pred obnovou sa automaticky uloží interná poistná kópia aktuálneho stavu. Systém uchová posledných 10 takýchto kópií.</div><form method="post" action="backup.php" enctype="multipart/form-data" class="form-grid single-column"><?=csrf_field()?><label>Súbor zálohy<input type="file" name="backup" accept="application/json,.json" required></label><label class="check-row"><input type="checkbox" name="replace" value="1"> Pred importom odstrániť existujúce projekty a verzie</label><label class="check-row"><input type="checkbox" name="restoreUsers" value="1"> Obnoviť aj administrátorské účty a heslá</label><button class="danger" onclick="return confirm('Naozaj chcete obnoviť dáta zo zálohy?')">Obnoviť zálohu</button></form></section><section class="card"><h2>Odporúčania</h2><p class="muted">Kompletnú zálohu stiahnite po každej väčšej zmene a pravidelne ju uchovávajte mimo servera. Používajte HTTPS a blokujte verejný prístup do priečinka <code>data</code>.</p></section></main></body></html>