<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';require_once __DIR__.'/../lib/mailer.php';ensure_storage();
$method=$_SERVER['REQUEST_METHOD'];$input=json_decode((string)file_get_contents('php://input'),true)?:[];$access=(string)($_GET['token']??$input['token']??'');$action=(string)($_GET['action']??$input['action']??'load');$mode='';$project=$access?find_project_by_token($access,$mode):null;
function sync_project_summary(array &$project,array $state):void{$w=$state['wedding']??[];$name=trim((string)($w['eventName']??''));$project['name']=$name!==''?$name:'Nový event';$project['weddingDate']=(string)($w['date']??'');$project['client']['name']=trim((string)($w['contactName']??''));if(trim((string)($w['email']??''))!=='')$project['client']['email']=trim((string)$w['email']);}
function validated_project_state(mixed $state,array $project):array{if(!is_array($state)||!isset($state['items'],$state['guests'],$state['wedding']))json_response(['ok'=>false,'error'=>'Neplatný formát projektu.'],422);if(!hash_equals((string)$project['id'],(string)($state['projectId']??'')))json_response(['ok'=>false,'error'=>'Dáta patria inému eventu. Obnovte stránku.'],409);return$state;}
function configured_root_url():string{if(BASE_URL!=='')return BASE_URL;$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$script=str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/api/project.php'));return $scheme.'://'.$host.rtrim(dirname($script),'/');}
if(!$project)json_response(['ok'=>false,'error'=>'Neplatný alebo zrušený odkaz.'],404);
if($action==='load'){$now=gmdate('c');if($mode==='edit'){$first=empty($project['meta']['firstOpenedAt']);$project['meta']['firstOpenedAt']=$project['meta']['firstOpenedAt']??$now;$project['meta']['lastOpenedAt']=$now;if(($project['status']??'not-opened')==='not-opened')$project['status']='editing';activity_add($project,$first?'client-first-open':'client-open','client',$first?'Klient prvýkrát otvoril editor':'Klient otvoril editor',[],1800);}else{$first=empty($project['meta']['shareFirstOpenedAt']);$project['meta']['shareFirstOpenedAt']=$project['meta']['shareFirstOpenedAt']??$now;$project['meta']['shareLastOpenedAt']=$now;activity_add($project,$first?'share-first-open':'share-open','viewer',$first?'Zdieľaný náhľad bol prvýkrát otvorený':'Zdieľaný náhľad bol otvorený',[],1800);}write_json(project_path($project['id']),$project);$state=$project['state']??[];if($mode==='share'){foreach(($state['guests']??[]) as &$g){if(!($project['share']['showDiet']??false)){$g['allergies']=[];unset($g['note']);}}}$locked=($project['status']??'')==='approved';json_response(['ok'=>true,'mode'=>$mode,'project'=>['id'=>$project['id'],'name'=>$project['name'],'status'=>$project['status'],'state'=>$state,'updatedAt'=>$project['meta']['updatedAt']??null,'locked'=>$locked,'review'=>$project['review']??null]]);}
if($method!=='POST'||$mode!=='edit')json_response(['ok'=>false,'error'=>'Tento odkaz nemá právo zapisovať.'],403);
if(($project['status']??'')==='approved'&&in_array($action,['save','share','submit'],true))json_response(['ok'=>false,'error'=>'Projekt je schválený a uzamknutý.'],423);
if($action==='save'){$state=validated_project_state($input['state']??null,$project);$project['state']=$state;sync_project_summary($project,$state);$project['status']=in_array($project['status']??'',['sent','revision-requested'],true)?'changed-after-send':'editing';$project['meta']['updatedAt']=gmdate('c');activity_add($project,'client-edit','client','Klient upravil návrh',['guests'=>count($state['guests']??[]),'items'=>count($state['items']??[])],1800);write_json(project_path($project['id']),$project);json_response(['ok'=>true,'savedAt'=>$project['meta']['updatedAt']]);}
if($action==='share'){$project['access']['shareEnabled']=true;if(empty($project['access']['shareToken']))$project['access']['shareToken']=token();$project['share']['showDiet']=(bool)($input['showDiet']??false);$project['meta']['updatedAt']=gmdate('c');activity_add($project,'share-enabled','client','Klient vytvoril alebo aktualizoval zdieľaný odkaz',['showDiet'=>$project['share']['showDiet']]);write_json(project_path($project['id']),$project);json_response(['ok'=>true,'shareToken'=>$project['access']['shareToken']]);}
if($action==='submit'){$state=validated_project_state($input['state']??null,$project);$pdfBase64=(string)($input['pdfBase64']??'');if($pdfBase64===''||strlen($pdfBase64)>40000000)json_response(['ok'=>false,'error'=>'PDF chýba alebo je príliš veľké.'],422);$pdf=base64_decode($pdfBase64,true);if($pdf===false||!str_starts_with($pdf,'%PDF-'))json_response(['ok'=>false,'error'=>'Neplatný formát PDF.'],422);$stamp=gmdate('Ymd-His');$dir=VERSION_DIR.'/'.$project['id'];if(!is_dir($dir))mkdir($dir,0775,true);$project['state']=$state;sync_project_summary($project,$state);$project['status']='sent';unset($project['review']);$project['meta']['submittedAt']=gmdate('c');$project['meta']['updatedAt']=$project['meta']['submittedAt'];activity_add($project,'submitted','client','Klient odoslal návrh organizátorom',['version'=>$stamp]);write_json($dir.'/'.$stamp.'.json',$project);if(file_put_contents($dir.'/'.$stamp.'.pdf',$pdf,LOCK_EX)===false)json_response(['ok'=>false,'error'=>'PDF sa nepodarilo uložiť.'],500);write_json(project_path($project['id']),$project);$adminUrl=configured_root_url().'/admin/project.php?id='.rawurlencode((string)$project['id']);$mailResults=mail_configured()?send_submission_notifications($project,$adminUrl):[];json_response(['ok'=>true,'submittedAt'=>$project['meta']['submittedAt'],'mail'=>$mailResults]);}
json_response(['ok'=>false,'error'=>'Neznáma akcia.'],400);
