<?php
declare(strict_types=1);
require_once __DIR__.'/../lib/storage.php';
require_once __DIR__.'/../lib/mailer.php';
ensure_storage();
$method=$_SERVER['REQUEST_METHOD'];
$input=json_decode((string)file_get_contents('php://input'),true) ?: [];
$access=(string)($_GET['token'] ?? $input['token'] ?? '');
$action=(string)($_GET['action'] ?? $input['action'] ?? 'load');
$mode='';$project=$access?find_project_by_token($access,$mode):null;
function sync_project_summary(array &$project,array $state):void{$w=$state['wedding']??[];$name=trim((string)($w['eventName']??''));$project['name']=$name!==''?$name:'Nový event';$project['weddingDate']=(string)($w['date']??'');$project['client']['name']=trim((string)($w['contactName']??''));if(trim((string)($w['email']??''))!=='')$project['client']['email']=trim((string)$w['email']);}
function configured_root_url():string{if(BASE_URL!=='')return BASE_URL;$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$script=str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/api/project.php'));return $scheme.'://'.$host.rtrim(dirname($script),'/');}
if(!$project)json_response(['ok'=>false,'error'=>'Neplatný alebo zrušený odkaz.'],404);
if($action==='load'){$now=gmdate('c');if($mode==='edit'){$project['meta']['firstOpenedAt']=$project['meta']['firstOpenedAt']??$now;$project['meta']['lastOpenedAt']=$now;if(($project['status']??'not-opened')==='not-opened')$project['status']='editing';}else{$project['meta']['shareFirstOpenedAt']=$project['meta']['shareFirstOpenedAt']??$now;$project['meta']['shareLastOpenedAt']=$now;}write_json(project_path($project['id']),$project);$state=$project['state']??[];if($mode==='share'){foreach(($state['guests']??[]) as &$g){if(!($project['share']['showDiet']??false)){$g['allergies']=[];unset($g['note']);}}}json_response(['ok'=>true,'mode'=>$mode,'project'=>['id'=>$project['id'],'name'=>$project['name'],'status'=>$project['status'],'state'=>$state,'updatedAt'=>$project['meta']['updatedAt']??null]]);}
if($method!=='POST'||$mode!=='edit')json_response(['ok'=>false,'error'=>'Tento odkaz nemá právo zapisovať.'],403);
if($action==='save'){$state=$input['state']??null;if(!is_array($state)||!isset($state['items'],$state['guests'],$state['wedding']))json_response(['ok'=>false,'error'=>'Neplatný formát projektu.'],422);$project['state']=$state;sync_project_summary($project,$state);$project['status']=$project['status']==='sent'?'changed-after-send':'editing';$project['meta']['updatedAt']=gmdate('c');write_json(project_path($project['id']),$project);json_response(['ok'=>true,'savedAt'=>$project['meta']['updatedAt']]);}
if($action==='share'){$project['access']['shareEnabled']=true;if(empty($project['access']['shareToken']))$project['access']['shareToken']=token();$project['share']['showDiet']=(bool)($input['showDiet']??false);$project['meta']['updatedAt']=gmdate('c');write_json(project_path($project['id']),$project);json_response(['ok'=>true,'shareToken'=>$project['access']['shareToken']]);}
if($action==='submit'){$stamp=gmdate('Ymd-His');$dir=VERSION_DIR.'/'.$project['id'];if(!is_dir($dir))mkdir($dir,0775,true);$project['state']=$input['state']??$project['state'];sync_project_summary($project,$project['state']);$project['status']='sent';$project['meta']['submittedAt']=gmdate('c');$project['meta']['updatedAt']=$project['meta']['submittedAt'];write_json($dir.'/'.$stamp.'.json',$project);write_json(project_path($project['id']),$project);$adminUrl=configured_root_url().'/admin/project.php?id='.rawurlencode((string)$project['id']);$mailResults=mail_configured()?send_submission_notifications($project,$adminUrl):[];json_response(['ok'=>true,'submittedAt'=>$project['meta']['submittedAt'],'mail'=>$mailResults]);}
json_response(['ok'=>false,'error'=>'Neznáma akcia.'],400);