name: Nahrať stránku na FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Stiahnuť súbory z GitHubu
        uses: actions/checkout@v6

      - name: Nahrať súbory na FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          port: 21

          local-dir: ./
          server-dir: /home/admin_kurkadesign/public_html/bukovina/

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.htaccess
            README.md
